### ISSUE TITLE
Not working in Thunderbird 52.4.0 (Linux)?

### ISSUE THREAD

**Issue by Leseratte10** [kee-org/browser-addon#103]
I have installed the Kee addon 2.0.0.25 in Firefox and it works perfectly with Keepass. Now I read I can also install this in Thunderbird (I have version 52.4.0 on Linux) to auto-fill mail passwords from Keepass. 

However, I can't find "Kee" in the Thunderbird store, it redirects me to the Firefox one, and when I manually download the addon file and try to install it in Thunderbird that fails. 

Does the new Kee 2.0 not work in Thunderbird? According to this Wiki page, https://github.com/kee-org/KeeFox/wiki/en-%7C-Thunderbird, I can't use an older 1.x version in Thunderbird and 2.0 in Firefox ...

**Comment by dlech** [comment]
Kee 2.0 cannot and most likely will not ever work with Thunderbird. You **can** continue to use the KeeFox 1.x extension with Thunderbird and Kee 2.x in Firefox.

**Comment by r2evans** [comment]
@dlech, I was about to ask another issue when I saw this last comment. To be sure I understand, this applies as well to 57 and 58beta? Huge bummer. Despite that, thanks for supporting as much as you have!

**Comment by dlech** [comment]
Yes, this applies to all versions of Thunderbird in the foreseeable future.

**Comment by adnion** [comment]
If you discover a nicer alternative combination of "browser + mail client + keepass" please let me know. Currently I use thunderbird and an old version of keepass with two different kee plugins.
