### ISSUE TITLE
Launch KeeFox button?

### ISSUE THREAD

**Issue by electricessence** [kee-org/browser-addon#104]
I really miss the ability to "Launch KeePass" from the browser plugin.  It now says OFF (obnoxiously).  Ultimately, I would prefer KeePass be logged out until needed (for a windows session).  So if I open my browser and do need to log into a website, then it would be nice to be able to launch keepass at that time.

**Comment by Leseratte10** [comment]
As far as I know, that is due to the new plugin interface in Firefox (WebAssembly) - that does not allow starting programs.

**Comment by electricessence** [comment]
I see. :(
