### ISSUE TITLE
[Request] Edit title / favicon

### ISSUE THREAD

**Issue by Symbai** [kee-org/browser-addon#110]
As of now in Kee 2.0.0.25 saving logins are pretty much pre-defined like the developers wants them to be. There is no way to edit/verify/changing a login before saving it to keepass.

Sometimes the title I would like to edit and othertimes the favicon isn't loaded (for whatever reason). So having an option to edit the title and reload the favicon would be much appreciated.

**Comment by Gracecr** [comment]
Perhaps it would be best to edit the entry in KeePass after it has been saved by KeeFox. It seems as if it would be just as much effort as manually editing the entry before saving it, plus KeePass needs to be open in order to use KeeFox.

**Comment by Symbai** [comment]
Well I've "fixed" the issue by using a third party plugin to update fav icons. Still weird that sometimes kee fails to crawl the favicon and other times it works.
