### ISSUE TITLE
Allow to set the default URL Match Accuracy for new entries

### ISSUE THREAD

**Issue by canihavesomecoffee** [kee-org/browser-addon#114]
This is a retake (most likely) of kee-org/KeeFox#647.

The default minimum URL matching accuracy was set to "hostname" up to KeeFox 1.4. After this it changed to domain.

Given that I have a lot of services on my work that are only differentiated by it's port or subdomain, I'm running into issues each time I add a new entry.

Would it be possible to make the default minimum URL matching accuracy configurable?

**Comment by alaunay** [comment]
+1, we have a lot of "service.domain.tld" entries, with only one user/pass each time, and kee gives me a dropdown list with all of them here... That's not good :(

**Comment by HobbledGrubs** [comment]
Absolutely, still a problem in Kee.  We have 1000's of *.domain.tld entries.  At the moment I search for collisions and manually change them to "Hostname. The URL must match the hostname (domain and subdomains) and port.

**Comment by otmarlendl** [comment]
FWIW, this is also affecting my usage of Kee.

My suggestion: "Domain" is usually perfectly fine for websites *outside* your own company, but "hostname" is the better choice for the dozens of internal accounts in various systems inside your own company.

So for me, the best solution would be to be able to configure a list of domains under which host-based matching should be done. If the current website does not fall under any of the configured domains, then default to domain-based matching.

**Comment by oliver-graetz** [comment]
+1 for being able to define domains that will always use "hostname".

**Comment by luckyrat** [comment]
Please see kee-org/keepassrpc#26 and kee-org/keepassrpc#27 instead because this is not a Kee addon issue but rather one for any KeePassRPC client.
