### ISSUE TITLE
HTTP Basic auth popup - empty content of popup

### ISSUE THREAD

**Issue by Perlover** [kee-org/browser-addon#115]
Hello,

The Kee 2.0.0.25 (KeePass RPC 1.7.0.0, Firefox 57.0 64bit)
The popup for choosing credentials of basic auth is empty
Workaround to see content of popup - i try to make selection of empty content and after i see credentials (a realm, a list of logins)

This bug appears everytime

**Comment by Perlover** [comment]
Second workaround: right mouse click in empty window of Kee Basic Auth popup

**Comment by mirh** [comment]
Duplicate of #71 maybe?

**Comment by Perlover** [comment]
Yes, it's same problem
But not "sometimes" - i would tell always :)
