### ISSUE TITLE
[Request] Add to whitelist context menu item

### ISSUE THREAD

**Issue by Symbai** [kee-org/browser-addon#119]
In most cases if kee fails to recognize a login its because the password/username field is not whitelisted.
While Kee integrates into firefox menu why not adding a context menu item if the user rightclicks in a text field to add the textfield ID to the whitelist?

This shouldn't be too difficult and would save a lot of trouble/time.

**Comment by luckyrat** [comment]
My main concern with this feature is that it might not be simple enough to make a real difference for most people. Perhaps a feature that allows the user to force the completion of a login into a given form field would be more helpful; we could then automatically whitelist the field as appropriate. That would need more work but overlaps with some research I'm going to do over the next few months anyway so I'm going to close this issue and we can revisit later in the year via the community forum if it is still applicable.
