### ISSUE TITLE
New connection authorization

### ISSUE THREAD

**Issue by top-cg** [kee-org/browser-addon#12]
Hello,

When 2 windows sessions are running in the same time, the windows showing the authorization code to be entered is showing on the 1st session which has been opened.
I don't know if it is Keepass or Keefox related but in the doubt, here is the information.
Nice app by the way ... this is the very first time i'm having troubles with it :)

Windows 10 
Firefox 54.0.1
Keepass 2.36

Antoine

**Comment by luckyrat** [comment]
Hi Antoine,

I don't think this can be a new problem for KeeFox 2.0. It has always been the case that multi-user setups require [custom port configuration](https://github.com/kee-org/KeeFox/wiki/en-%7C-Options-%7C-KPRPC-Port). I suppose if you're really lucky it could work a few times but eventually you'll get bitten if you try to have multiple KeePass instances running on the same computer at the same time.

Let us know if that doesn't resolve the issue.
