### ISSUE TITLE
Basic auth on Linux/Ubuntu: blank popup

### ISSUE THREAD

**Issue by kyriog** [kee-org/browser-addon#125]
Hi,

When I go to a website which requires a basic auth (".htaccess auth") and having a matching keepass rules, Kee opens a blank popup:
![capture d ecran de 2017-12-20 18-13-11](https://user-images.githubusercontent.com/629831/34219580-eeb5d294-e5b1-11e7-866e-77fd8ebd7b73.png)

If I close this popup, Firefox does not show the "classic" auth popup, I have to disable Kee addon in Firefox to be able to login manually.

I'm using:
Ubuntu 17.10
Firefox 57.0.1
Keepass 2.36

Everything works well for "in page" logins.

Thanks for your help :)

**Comment by pfoo** [comment]
#71 
This is a firefox bug, right mouse click or resize the window in order to display data.
