### ISSUE TITLE
Kee doesn’t work, just showing “OFF” logo

### ISSUE THREAD

**Issue by Fred-N** [kee-org/browser-addon#132]
Kee doesn’t work, it just shows the “OFF” logo and message “You are not logged in to your password database”, but I am logged in KeePass with PRC plugin installed.

I am getting nuts with it.
Windows 10
KeePass: 2.37
Kee: 2.0.0.25
Firefox: 57.0 (64 bit)
KeePassRPC 1.7.3 (detected in KeePass without client in the list)
Avast antivirus (tried also deactivated)

**Comment by Fred-N** [comment]
resolved after a massive Windows10 upgrade

**Comment by antimatter84** [comment]
Same problem, but running Windows 7. Kee icon just shows "OFF" and won't connect to KeePass application. KeePass is running with the latest RPC plugin.

KeePass 2.38
KeePassRPC 1.7.3
Kee 2.3.19.1
Firefox 59.0.1
