### ISSUE TITLE
Kee showing icon on fields with the atrribute disabled="disabled" set

### ISSUE THREAD

**Issue by jdunn0** [kee-org/browser-addon#137]
When an input field has the attribute disabled="disabled", the field cannot be edited so the Kee Icon should not appear on it.
However that seems to happen when visiting https://ifttt.com/settings while logged in to IFTTT as this image shows:
![ifttt settings - account](https://user-images.githubusercontent.com/9695075/34902935-32b66de2-f7db-11e7-99fa-97a02c250056.png)
The password field HTML code is:
`<input name="password" id="password" value="****************" disabled="disabled" class="display" type="password">`

The field is just for display purposes as it doesn't actually contain the user's password and you need to click "Change Password" to go to the actual page for changing the password.

One could argue that as it's a settings and account update page that the Kee Icon shouldn't appear at all but from reading other issues, it appears that point is best left to the forum.
It seems though that even on a login form, the Kee Icon shouldn't appear on disabled fields.

**Comment by luckyrat** [comment]
Ideally this would have been created as a post for discussion on the forum but I'll implement the only feasible improvement now and if any further discussion is needed, a new post can be opened at that time.

Kee 2.2 will no longer change the mouse cursor when hovering over the disabled icon and form field.

It's not possible to avoid inserting the icon unless we implement an efficient method of monitoring for changes to attributes. Mutation observers are one possible approach we could take but I won't consider making such widespread changes in isolation - there are a variety of issues with the current icon implementation and I will only consider implementing a complete exclusion for disabled attributes as part of a larger improvement to this part of Kee.

**Comment by jdunn0** [comment]
> Ideally this would have been created as a post for discussion on the forum
Huh, I purposely created this as a GitHub issue as it seemed like a clear easy to fix bug without any discussion necessary.
The disabled attribute appears to be set via the HTML of the page and not by any Javascript so there should not be any need to monitor for changes to fields in this case.
Just check when adding the Kee Icon to fields for the disabled attribute and don't do anything with the field if that is set.
