### ISSUE TITLE
Kee cannot connect to KeePass if proxy switching plugin installed

### ISSUE THREAD

**Issue by slavakrampetz** [kee-org/browser-addon#138]
I have installed FoxyProxy extension for switch between different proxies.
https://getfoxyproxy.org/

This extension allows to have different proxy configurations and switch between these configs on-the-fly. It stores last selected proxy on closing FireFox. 

When I start FireFox using any external proxy, Kee cannot find KeePass. After switching proxy off, Kee can connect to KeePass.

**Comment by auanasgheps** [comment]
It is expected: Kee uses local network communication to connect to KeePass desktop application.
Whitelist _localhost_ or _local_ domains in your proxy extension, it should make the trick. I have another Proxy extension on Chrome and by doing this I can use Kee.

**Comment by skapytek** [comment]
> It is expected: Kee uses local network communication to connect to KeePass desktop application. Whitelist _localhost_ or _local_ domains in your proxy extension, it should make the trick. I have another Proxy extension on Chrome and by doing this I can use Kee.

This is not working in Firefox.
Its still a problem today. If Foxyproxy is enabled for all domains (except localdomain, localhost, and so on) its still not working. Any ideas?
