### ISSUE TITLE
can't get connection to keepass

### ISSUE THREAD

**Issue by pcause** [kee-org/browser-addon#14]
Just installed this alpha on firefox nightly. i also added the new keepassrpc as well.  keefox says that it is off and i am not logged in.  i am on win10 (Insider build) x64

**Comment by luckyrat** [comment]
The new KeePassRPC as in v1.7.1? I've not tested the current alpha with that version but will most likely release another alpha within a week or so which will work with that version (maybe sooner).

The alpha version should work with KPRPC 1.7.0 but naturally it hasn't been well tested ... and not at all in any Firefox build newer than the one available when the alpha was created (56.something)

**Comment by pcause** [comment]
I was installing this alpha (2.0.0.alpha 3) with the keepassrpc 1.7.1.

thanks for the reply.

**Comment by Aetf** [comment]
Hi, I'm facing the same issue.

Versions:
- Windows 10 build 16232
- Firefox Nightly 57.0a1 (2017-08-20) (64-bit)
- KeePass 2.35
- KeePassRPC 1.7.2
- KeeFox 2.0.0.3

In the browser console, the error says
```
An attempt to setup the KPRPC secure channel has failed. It will not be retried for at least 10 seconds. If you see this message regularly and are not sure why, please ask on the help forum. Technical detail about the problem follows: TypeError: configManager.current.KPRPCStoredKeys is undefined
```

**Comment by luckyrat** [comment]
Please try Kee(Fox) 2.0.0.4. It's not without problems in Firefox (although maybe no more so than alpha 3) but I don't see any trouble with the connection to KeePass.

**Comment by pcause** [comment]
Just installed and it connected and filled in my github credentials so that I could respond.   Will post further as I see issues, if any.

**Comment by pcause** [comment]
forgot to mention, using rpc version 1.7.2

**Comment by Aetf** [comment]
Upgrading to 2.0.0.4 works for me. 👍

**Comment by luckyrat** [comment]
Great! Feel free to re-open or open a new issue if you have similar problems in future.

**Comment by bizarrochris** [comment]
I'm facing the Same issue:

You are not logged in to your password database. Launch KeePass to enable Kee

- Windows 10 (Build 15063)
- Kee 2.0.0.17
- KeePassRPC 1.7.3
- KeePass 2.37
- KeePassRPC Port (both in FF and in RPC ist 12513)
- FF Dev Edition 57.0b13 (64-bit)

Any Idea whats happening? (RPC Plugin shows 0 Connected clients -> but I also dont get any connection requests)
