### ISSUE TITLE
Create "stub" entry in database for any web page (even if without any password detected)

### ISSUE THREAD

**Issue by schubidoo** [kee-org/browser-addon#151]
I would love to see the ability to create an entry in the database for **any** web site, even if no login is detected. There are two reasons for this:

1. Right now, an entry can only be created from Kee if a password etc. has been entered and the form has been **posted**.
There are, however, quite a few web pages that seem to use forms, but then use some kind of script to transmit the data (which is probably bad style), instead of POST. In those cases, Kee seems to find the fields (autofilling them, after manually generating the entry, does work), but the option to save the logins never comes up because the POST is not detected. The manual triggering of saving the credentials (in that case before the "send credentials" button is pressed) would provide a nice workaround for those sites.
2. Sometimes the field detection does not work at all, because the site is using some nasty scripting. In those cases, I would still like to generate an entry in the database, and fill the password manually, simply so that I do not forget them. Generating an entry with Kee directly from the site, even if I have to edit it afterwards in Keepass to add PW and login, is a) more convenient, and b) it could automatically add the web site icon, which is currently extremely tedious to do manually in Keepass.
This would also be useful to conveniently generate an entry for any site just to save some important information which is never entered, but that you would still like to associate with the web site or simply with the company behind the site (So you can, say, store a pin code for your company's back door code lock conveniently with a nice entry that has the company logo as icon).

So the proposed functionality would be like this:
- There is always an option in the Kee main menu to save the current site, even if no recent login activity has been detected. If no login/pw fields are found, a "stub" entry is generated, just with web site address as address, the web site title as name, and the web site icon as icon.
- If a login and password field is found, then these fields are also filled with whatever the user has entered by that point (but I am not sure if that is possible based on the firefox security procedures)

(The title seems a bit similar to #144, but it is a very different proposal, therefore I opened a new issue. In particular, #144 (which I find also interesting) would require creation of generalized fields in the database entry, this proposal is much simpler and does not change the structure of the data that is saved)

**Comment by luckyrat** [comment]
Per the recently announced [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please post this message in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.
