### ISSUE TITLE
Firefox: Settings for specific website are centered, while main settings are left-aligned

### ISSUE THREAD

**Issue by Id3aFly** [kee-org/browser-addon#152]
Hey everyone,

I just recognized following layout "bug" in firefox:
If I go to the settings and choose "Show Options for all websites", everything is left aligned.
If I choose "Show options for specific website" everything is centered.

Could you please unify the layout?

Thank you
Id3aFly

**Comment by luckyrat** [comment]
Yeah it looks like Firefox has variable width options compared to Chrome's fixed (or at least low maximum) width.

IIRC the alignment is via flexbox or grid layout.

We should prevent the reduced content for the specific website search view causing the control fields from moving to a more central position.

@Id3aFly If you know CSS (or want to spend some time learning, it should be an "easy" fix... as far as any alignment issues in CSS are easy anyway).

**Comment by Id3aFly** [comment]
I'm not that familiar with CSS, so I don't want to corrupt anything.
Apart from that, how would I be able to test it?

**Comment by luckyrat** [comment]
You'd basically test it by loading the "fixed" version in your local browsers. You need something like Firefox Developer Edition (or Nightly) to do this. Assuming you already have that browser available, building a test version of Kee shouldn't be too hard (basically get the source code and then run a command on your command line) - more details and next steps are in the README: https://github.com/kee-org/browser-addon/blob/master/README.md

That's not a step-by-step guide to your first ever piece of code development though so you'd want to read around a bit elsewhere if that's not something you've done before.

**Comment by Id3aFly** [comment]
Thank you, I'll try to get into that topic. But that takes a while.
Someone else should close this CSS thing.

**Comment by luckyrat** [comment]
Moving options into a separate tab in order to work around a new Chrome bug has made this issue go away.
