### ISSUE TITLE
disable animation on browser focus 

### ISSUE THREAD

**Issue by freeseacher** [kee-org/browser-addon#154]
Please add options to disable animation
it is very annoying sometimes.
especially on frequent context switching
[111.mkv.zip](https://github.com/kee-org/browser-addon/files/1692336/111.mkv.zip)

**Comment by luckyrat** [comment]
Thanks for your interest in helping to improve Kee.

GitHub issues are for clear and well defined changes to project behaviour, appearance and code.

Issues may not always be worked on immediately but if there is not a clear plan and need for a change the issue may be closed, at least until the need or specification is more clearly evaluated on the community forum.

If you have not been asked to create an issue here and are unsure if creating an issue is the best way forward, please use https://forum.kee.pm instead.

In particular, please note that initial discussion regarding any of the following should begin on the forum:
* Help using Kee
* Documentation
* Bug reports
* Change proposals
* Feature requests
* Questions/comments about security(*)
* Help developing/building Kee

The full contribution and support guidelines can be found at: https://github.com/kee-org/browser-addon/blob/master/CONTRIBUTING.md

Thank you for following these guidelines - it will help us to keep each discussion focussed in a single place and improve the project more quickly.

(*) Note that sensitive issues should always be addressed via a private contact - see https://forum.kee.pm for how to do this.
