### ISSUE TITLE
Popup for HTTP authentication not showing all entries

### ISSUE THREAD

**Issue by casperklein** [kee-org/browser-addon#155]
When opening a website with HTTP authentication, a popup window is opened to select the right entry.

I have seven entries for a specific domain. But in the popup window only four entries are visible. Since there is no possibility given to scroll, only resizing the window shows the rest of the entries.

It would be nice, if the popup window size could be customized depending on the amount of entries.

**Comment by luckyrat** [comment]
Thanks for your interest in helping to improve Kee.

GitHub issues are for clear and well defined changes to project behaviour, appearance and code.

Issues may not always be worked on immediately but if there is not a clear plan and need for a change the issue may be closed, at least until the need or specification is more clearly evaluated on the community forum.

If you have not been asked to create an issue here and are unsure if creating an issue is the best way forward, please use https://forum.kee.pm instead.

In particular, please note that initial discussion regarding any of the following should begin on the forum:
* Help using Kee
* Documentation
* Bug reports
* Change proposals
* Feature requests
* Questions/comments about security(*)
* Help developing/building Kee

The full contribution and support guidelines can be found at: https://github.com/kee-org/browser-addon/blob/master/CONTRIBUTING.md

Thank you for following these guidelines - it will help us to keep each discussion focussed in a single place and improve the project more quickly.

(*) Note that sensitive issues should always be addressed via a private contact - see https://forum.kee.pm for how to do this.
