### ISSUE TITLE
Console Debug Spam

### ISSUE THREAD

**Issue by KN4CK3R** [kee-org/browser-addon#156]
Could you please remove the debug output from the released version? I often use the Firefox developer console and the debug logs of this addon are a little bit annoying:

```
no password field found in this form
In browser content page script, received message from background script
scanForOrphanedFields took: 1
Finding matches in a document. readyState: complete
findMatches processing 1 forms
about to get form fields
domtype: checkbox
proccessing...
domtype: checkbox
proccessing...
domtype: checkbox
proccessing...
[...]
```

**Comment by luckyrat** [comment]
Thanks for your interest in helping to improve Kee.

GitHub issues are for clear and well defined changes to project behaviour, appearance and code.

Issues may not always be worked on immediately but if there is not a clear plan and need for a change the issue may be closed, at least until the need or specification is more clearly evaluated on the community forum.

If you have not been asked to create an issue here and are unsure if creating an issue is the best way forward, please use https://forum.kee.pm instead.

In particular, please note that initial discussion regarding any of the following should begin on the forum:
* Help using Kee
* Documentation
* Bug reports
* Change proposals
* Feature requests
* Questions/comments about security(*)
* Help developing/building Kee

The full contribution and support guidelines can be found at: https://github.com/kee-org/browser-addon/blob/master/CONTRIBUTING.md

Thank you for following these guidelines - it will help us to keep each discussion focussed in a single place and improve the project more quickly.

(*) Note that sensitive issues should always be addressed via a private contact - see https://forum.kee.pm for how to do this.
