### ISSUE TITLE
KeeFox2 not working without installed KeePass using remote KeePass via tunneled TCP port

### ISSUE THREAD

**Issue by AndriiZ** [kee-org/browser-addon#157]
I have installed KeePass and KeeFox2 on my desktop. KeeFox2 perfectly working with KeePass
Than, I have installed KeeFox2 on my laptop
I have tunneled tcp port 12546 via PuTTY, and I can connect to the port
Unfortunately, KeeFox2 on laptop can not connect to remote KeePass

**Comment by luckyrat** [comment]
Please post questions on the forum: https://forum.kee.pm
