### ISSUE TITLE
Feature Request: allow blacklisting hidden form fields

### ISSUE THREAD

**Issue by gshegosh** [kee-org/browser-addon#158]
Example website: https://e-kantorpolski.pl/

There are two login forms and they only differ by value of a hidden field. If I'd like to have the right side form filled in - there's currently no way to blacklist the left side one.

Ability to list hidden field values to blacklist a form would solve this.

**Comment by luckyrat** [comment]
I think this situation might be a bit too niche to justify the effort of rewriting the form detection code to take account of hidden form fields and introducing the corresponding performance impact for all users.

My current thinking is that this sort of issue would be better solved by a more general system that takes into account the position in the page of a form (or form field) but it's a rough idea at the moment and not likely to be fleshed out or implemented soon.

Feel free to re-post this discussion on the [community forum](https://forum.kee.pm) if you want to get other people involved.

**Comment by gshegosh** [comment]
Would a PR be considered, if I found time to work on it myself?

**Comment by luckyrat** [comment]
I'm afraid not without some stronger signals from the community that this is a problem on enough websites to justify the extra code; it's more about the addition of options that few people will ever use, the small amount of extra processing time for every form Kee encounters and the added risk of people misconfiguring things in a way that's hard for other people to help them diagnose than it is about the amount of time it will take to implement. Although the latter is a factor of course so if the other factors can be balanced against a strong enough need for the feature, a PR would at that time be helpful.
