### ISSUE TITLE
Option for HTTP Basic Auth only

### ISSUE THREAD

**Issue by raubv0gel** [kee-org/browser-addon#161]
There should be an option (check box) in the Kee tab in KeeFox to allow the KeePass entry for HTTP Basic Auth only. A second option (check box) should be to exclude the KeePass entry for HTTP Basic Auth.

This would be useful because I have a KeePass entry that is used for HTTP Basic Auth and one for the Login on the website itself (something like two factor authentication). Both entries have the same URL (exact match mostly), therefore both entries are matched if browser invokes HTTP Basic Auth.

**Comment by luckyrat** [comment]
I'm not yet convinced that we'd want to do this but if you post your suggestion on the [community forum](https://forum.kee.pm) we can see if it triggers a discussion leading towards a suitable solution for the issue you're trying to solve.
