### ISSUE TITLE
Add OTP secondary page

### ISSUE THREAD

**Issue by Stonedestroyer** [kee-org/browser-addon#170]
Is there any way after you put in login and password for KeePass to fill in a variable like OTP number? I noticed the recent Firefox patches disallowed doing two pages authentication but is it possible to have it on Chrome?

**Comment by luckyrat** [comment]
[OTP](https://forum.kee.pm/t/kee-and-otp-codes/1037/2) would be a different issue from [automatic multi-page login support](https://github.com/kee-org/browser-addon/issues/6). There's no difference between Chrome and Firefox in this regard (just between the old Firefox 56 and new Firefox 57+)
