### ISSUE TITLE
Protected directory - cannot scroll

### ISSUE THREAD

**Issue by dmsims** [kee-org/browser-addon#174]
With the latest release

Access a protected directory (at the webserver level) mine is Apache

You are presented with a Kee Network authentication panel with four entries, the one I need is below these

It used to be possible to scroll and select the correct one

![kee authentication](https://user-images.githubusercontent.com/4712953/38469909-f441c892-3b53-11e8-8fbc-72366efad1b4.png)

**Comment by luckyrat** [comment]
https://forum.kee.pm/t/popup-for-http-authentication-not-showing-all-entries/738/5

Please continue discussion on that forum thread if required.
