### ISSUE TITLE
Can't install in 59.0.2 (64-bit) on Windows 10

### ISSUE THREAD

**Issue by rektboi** [kee-org/browser-addon#178]
So I just switched back from Chrome to FF. I tried to install Kee from mozilla.org and I got "This add-on requires a newer version of Firefox (at least version 56.0). You are using Firefox 52.0." But I'm actually running 59.0.2 (64-bit) . On my Linux machine it just installed normally as one would expect.
I tried installing from the .xpi directly but FF won't let me, even with the "xpinstall.signatures.required" switched to off. 
Any ideas? Thanks.

**Comment by luckyrat** [comment]
You probably downloaded the ESR (enterprise/business) version by mistake. Double-check your version number in "Help > About Firefox" and make sure you're not running from a different installation location than you expect.

PS: In future, or if this doesn't help resolve the problem, please post support questions on the [community forum](https://forum.kee.pm).
