### ISSUE TITLE
"Authorise a new connection" window when Kee is running in another Windows user session

### ISSUE THREAD

**Issue by HupfderFloh** [kee-org/browser-addon#179]
System:
- Windows 10 Professional x64 version 1709
- Firefox 59.0.2
- KeePass 2.28
- KeePassRPC 1.7.3.0
- Kee 2.3.19.1

Precondition:
- 2 Windows user accounts (let's call them A and B) are logged in simultaneously (using "switch user" to alternate between them).
- the two Windows Accounts do have the same user name, one being a local account and the second being an Active Directory account
- on Account A, Firefox is opened with Kee installed (for the local user). Also KeePass is opened with database A.kdbx
- on Account B, Firefox does not have Kee installed and the browser is not open either.

Steps to reproduce:
- on Account B (currently active), open KeePass (with intent to open database B.kdbx for use in another browser)
- observe that the "Authorise a new connection" pops up on account B (before being able to open a database).
- Attenpting to click the "Close" button just opens a second pop-up immediately.
- after closing KeePass altogether on account B and switching back to account A, observe that a number of new Firefox tabs matching the "Authorise a new connection" attempts has been opened.

Expected result:
- running windows sessions should not affect each other (for functional and possibly security concerns).
- Kee should be aware of the user IDs the relevant processes (KeePassRPC, KeePass, Firefox) are running under and ignore mis-matching processes
- possibly the filtering is done already, but based on the user name only (not tested with differently named accounts)

**Comment by luckyrat** [comment]
Please see the community forum: https://forum.kee.pm/t/multiple-user-settings/460/3?u=luckyrat

KeePassRPC uses TCP/IP to communicate since this is the only method available to both Firefox and KeePass, hence knowledge of process IDs, users, etc. is impossible.
