### ISSUE TITLE
References are not resolved

### ISSUE THREAD

**Issue by swiehr** [kee-org/browser-addon#181]
References are not resolved anymore, e.g. in matched login entries opening from a login form I see entries like `{REF:U@.....} - Keepass Entry name` instead of `username - Keepass Entry name` whereever references are used for the login and when filled in this fills the reference string instead of resolving it.

This used to work before, when using KeePass Auto-type for the browser window the login is correctly resolved & filled.

Used version Kee 2.3.19.1, KeePassRPC 1.8, KeePass 2.39, Firefox 59.0.3

**Comment by akuntsch** [comment]
I think this might be an issue with the new KeePassRPC version 1.8 rather then an issue with the browser addon.

**Comment by EmTeedee** [comment]
This is definitely caused by KeePassRPC, but it is a security feature.
See https://forum.kee.pm/t/placeholder-handling/1100

**Comment by Semnodime** [comment]
**You can set the database default behavior to enable placeholders by default for all entries.**
This can be **dangerous** ( _as dangerous as before_ ) and there is a reason why placeholders have been disabled by default as **placeholders can leak information such as other database contents**.

Instructions to enable placeholders database wide
-----------------------------------------------------------
KeePass Window > Menu: «File» > Database Settings... > Tab: «Kee» > Tab: «KeePass placeholders» > RadioButton: «Enable» > Button «OK»
![Instructions to enable placeholders database wide](https://user-images.githubusercontent.com/19511852/40032378-2be2a6d8-57f4-11e8-964f-1114fc888a8f.png)

AFAIK the only **more secure alternative is to **individually enable placeholders**** per entry.

**Comment by swiehr** [comment]
Thanks for the numerous replies and clarification, I think this issue can be closed as "it's not a bug, it's a feature"
