### ISSUE TITLE
* Bug reports - Reference not working

### ISSUE THREAD

**Issue by mbrucco** [kee-org/browser-addon#182]
Kee do not "translate" referenced value from keepass.

Keepass entries

### Entry 1, having ID 2688DB130BAC4063B5490BCAD00504F5
![immagine](https://user-images.githubusercontent.com/13663711/40239193-a0bff8ca-5ab5-11e8-8624-a9027a4728d7.png)
![immagine](https://user-images.githubusercontent.com/13663711/40239225-c418aee8-5ab5-11e8-9e6d-424304d38ad7.png)
### Entry 2, having ID A747D4EAD3FF9440A156DB1BF6DC5A00
![immagine](https://user-images.githubusercontent.com/13663711/40239304-02fd169e-5ab6-11e8-9a3d-f6b74a7bc522.png)
![immagine](https://user-images.githubusercontent.com/13663711/40239330-0d8d6ea6-5ab6-11e8-97de-97cf5e12f5bd.png)

When I navigate to URL "http://localhost:52014/" kee correctly identify that right entry is the second one, but when it fill form it is expected to retrieve UserName and Password from Entry1 (referenced) but it show:

![immagine](https://user-images.githubusercontent.com/13663711/40239533-9d24a67e-5ab6-11e8-972a-ff23bb5c9ccd.png)

**Comment by dlech** [comment]
Duplicate of #181?

**Comment by mbrucco** [comment]
yes sorry... solved with db settings
