### ISSUE TITLE
Nonstandard form field name/id not recognized 

### ISSUE THREAD

**Issue by TitanSpirit** [kee-org/browser-addon#183]
I studied carefully topic on https://github.com/kee-org/KeeFox/issues/367 because my issue is very similar however I am not able to succeed after few hours of inspecting configuration.
KeePass 2.39.1
Kee 2.3.19.1
KeePassRPC 1.8.0.0
Firefox 60.0.1 64bit

Trying to login to my anti-theft service from ESET on https://login.eset.com
From page source I picked up manually fields:

ID: body_LoginCtr_txtLoginEmail
NAME: ctl00$body$LoginCtr$txtLoginEmail

          <table class="login form_table">
            
                <tr>
                    <td class="l">
                        <label for="body_LoginCtr_txtLoginEmail">
                            Adres e-mail:
                        </label>
                    </td>
                    <td class="i">
                        <input name="ctl00$body$LoginCtr$txtLoginEmail" type="text" id="body_LoginCtr_txtLoginEmail" tabindex="1" onchange="ESET.ValidateForm(this);" />
                        <span id="body_LoginCtr_rfvLoginEmail" class="validator" style="visibility:hidden;"></span>
                    </td>
                </tr>
            
                <tr>
                    <td class="l">
                        <label for="body_LoginCtr_txtLoginPassword">
                            Hasło:
                        </label>
                    </td>
                    <td class="i">
                        <input name="ctl00$body$LoginCtr$txtLoginPassword" type="password" id="body_LoginCtr_txtLoginPassword" tabindex="2" onchange="ESET.ValidateForm(this);" />
                        <span id="body_LoginCtr_rvfLoginPassword" class="validator" style="visibility:hidden;"></span>
                    </td>
                </tr>

1. I tried add an entry for that url, KeeFox tab, Form fields subtab and entered Name "ctl00$body$LoginCtr$txtLoginEmail", Id "body_LoginCtr_txtLoginEmail", for page 1 of that form. KeeFox still does not detect the User ID field.
2. Tried to add in firefox extension settings for all websites custom fields name. No effect.
3. Tried same as in 2. but for specified website https://login.eset.com. No effect.
4. Removed whole entry in KeePass for ESET with added custom fields in extension settings, logged by manually typing credentials, but it does not recognize fields and does not offer a way to safe last password. 

I used to have Chrome + ChromeIPass + KeePassHTTP and everything worked fine as there was a useful feature of picking up credentials fields just by clicking and extension automatically added it to entry in keepass. Is such feature considered in the future? 

Please help in setting up correctly to login in ESET with Kee.

**Comment by Pantamis** [comment]
Hi,

For the first point : yes, you have to do this. The names of the fields are not well design to me ... (you can try to omit them)

Then you need to add the ids of the fields (they are obviously less messy than names) in Kee whitelist of text fields, in website custom fields or not. ids must be separated with commas without spaces.

And it should work.

By default, Kee doesn't attempt to fill anything if it is not sure that the forms contain username/password fields, whitelist overwrite this.

Notice : if you try to remember the credentials after manually typing, you have to select "save last login" just after you validate them in Kee menu. But if the website redirects you many times it can fail so you have to manually create the entry.

Hope this help,

Best,

**Comment by luckyrat** [comment]
Thanks @Pantamis .

@TitanSpirit if you're still having trouble, please check out the [community forum](https://forum.kee.pm) for additional help.
