### ISSUE TITLE
[Finding forms] based on classes, no IDs available

### ISSUE THREAD

**Issue by VlkaFenryka** [kee-org/browser-addon#189]
Example: [https://login.easybell.de](url)

How am i able to configure the finding forms logic to autofill my credentials, when there are "only" bootstrap classes?

- There are no NAME and ID attributes for the FORM
- The INPUTs for username and password do not have ID attributes

```
<form method="POST" action="https://login.easybell.de/login" accept-charset="UTF-8" class="form-signin" role="form">
<input name="_token" value="t0xqM0Ju8hfqDnbeM6GQ9V9ZtgpmJFTeMinpHDk5" type="hidden">
<h3 class="form-signin-heading">Kundenportal Login</h3>

<input class="form-control" placeholder="Kundennummer" onfocus="interruptCountdown()" required="" name="id" type="text">
<br>
<input class="form-control" placeholder="Passwort" onfocus="interruptCountdown()" required="" name="password" value="" type="password">
<br>
<button type="submit" class="btn btn-lg btn-default btn-block" onclick="interruptCountdown()">
    <i class="fa fa-sign-in"></i><span>Login</span>
</button>
<br>
<div class="text-center clearfix">
    <a class="btn btn-link" href="/passwortVergessen">Passwort vergessen?</a>
</div>
</form>
```

**Comment by luckyrat** [comment]
There doesn't seem to be any reason that form wouldn't work with Kee, with no need for worrying about classes. Please test with [v3.0](https://forum.kee.pm/t/kee-vault-and-kee-version-3-0/2025/) (either in [beta](https://forum.kee.pm/t/beta-testing-the-kee-browser-extension/2022) or when it is released and then post more details about what you've tried already on the [community forum](https://forum.kee.pm) if you still can't get it to work.
