### ISSUE TITLE
Keepass is really secure (can simply be breach like this)? 

### ISSUE THREAD

**Issue by redcat22** [kee-org/browser-addon#190]
Hi
Here is an example (link below) how to breach keepass. This issue was already overcome?
How secure is Kee addon regarding this security issue?

https://www.youtube.com/watch?v=rxluAFAXk0o

**Comment by dlech** [comment]
Kee uses https to communicate between the browser and KeePass, not the clipboard, so it is not vulnerable to clibpoard logger attacks.
