### ISSUE TITLE
Kee does not match properly

### ISSUE THREAD

**Issue by OvalMedia** [kee-org/browser-addon#191]
I have hundreds if not thousands of passwords in my keepass database. A lot of them for local development (websites, shops etc.). I am running those dev sites with a .local domain. 

I have passwords stored with a proper backend url (e.g. https://www.example.com.local/backend). These URLs are very unique yet whenever I get to the login page of my backend kee is showing me entries from a lot of other entries in my database which have a completely different URL set in their database entry.

How can I configure kee to EXACTLY match those entries?

**Comment by Havokdan** [comment]
Maybe what you want is:

1 - Go to the entry you want and click Enter;
2 - Go to tab "Kee> URLs" and select "Hostname" or "Exact"

**Comment by OvalMedia** [comment]
Ok, but I have thousands of entries in my database. Is there a way to set this globally?

**Comment by Havokdan** [comment]
I do not know, the standard for me is ideal behavior, one or another input that I needed to change.

**Comment by luckyrat** [comment]
@OvalMedia See the new features described in "Enhanced entry URL matching control" in the latest KPRPC release notes on the forum: https://forum.kee.pm/t/release-notes-keepassrpc-1-8-0/1107

Depending on when and how you set up your entries, you will have varying levels of success by setting the global options but it will definitely apply for newly created entries.

.local is an unusual domain. I'm confident that the underlying domain handling code in KPRPC is treating it per the specification but it's possible that the real-world use cases when it comes to matching URLs would benefit from adjustment. It's not something I've used myself yet so don't really have any input on how people want it to behave. Once you've had a look at the global options mentioned above, I'm happy to discuss further if there are issues specific to your use-case of the local domain that might be improved in a future version. However, I would prefer such discussion to take place on the community forum and if/when a new feature or behaviour change gets identified, we can then move the concrete requirement to GitHub issues.
