### ISSUE TITLE
Auto-type for searched and selected entry

### ISSUE THREAD

**Issue by ggeorgg** [kee-org/browser-addon#193]
If I search for an entry and then click this entry, the website is just opened. I expected that the website is opened and the credentials of this entry are auto filled. I know the Kee setting to automatically fill in the credentials, but I can not use this, because I have several entries which do have the same url.
In Keefox this has been a great feature for me. (I think also for others)

I have already annotated this in [#145](https://github.com/kee-org/browser-addon/issues/145#issuecomment-371276518). 
Afterwards I have opened a new topic in https://forum.kee.pm/t/auto-type-for-searched-and-selected-entry/1074.
Unfortunately, up to today nobody answered on my topic. 
What do you think, would it be hard to implement this behaviour? The needed functions should already be there, right?

Have a nice day!

**Comment by luckyrat** [comment]
Thanks for the extra information. I've now replied to your forum topic.
