### ISSUE TITLE
Text field insert button needs offset options

### ISSUE THREAD

**Issue by VulcanTourist** [kee-org/browser-addon#195]
Kee isn't the only Firefox extension that places an insert button into or around text fields.  As such, it is possible if not likely that Kee's insert button will conflict with another extension's button.  In my instance, Kee's button certainly does conflict with another extension's button, that of InformEnter, making Kee's button inaccessible because the other InformEnter's button overlays it almost entirely.

Options for offsetting the location of the button are sorely needed.

**Comment by luckyrat** [comment]
I figured it was inevitable that something like this would crop up eventually, hence the "Matched login entries" feature that can invoke the entry chooser panel without the need to click on the Kee icon in each field.

I'm afraid that it's just not feasible for each extension to offer options to this level of detail, nor do I expect many users would enjoy the chore of arranging such a configuration (and maintaining it when another extension gets upgraded to include such an icon). 

I think that the most sensible way this could be resolved would be if browser developers created a dedicated API for controlling the existence of such icons within fields (or other page elements too?) and all extensions like Kee start using that new feature to request the injection of their icon (it may well need to behave similarly to the overflow addons menu such that if too many are displayed for the width of field, the unlucky addons get pushed under an extra dropdown click).

I'll be happy to make changes to Kee to fit within such a standard if it were to be developed but until then I don't think there's much point in keeping this specific issue open. Feel free to discuss creating a standard elsewhere and poke me to contribute, although I'll be honest up front that I think there are more important gaps in the browser API so I wouldn't be advocating for a lot of resources to be spent on this at the moment.

**Comment by VulcanTourist** [comment]
Had you investigated the InformEnter+ extension that I referenced you would have discovered, as I did much later after creating the ticket, that its developer had already created a simple but inventive solution to the problem; either it was implemented after I made the ticket or was unknown to me at the time.  Right-clicking on its overlaid button relocates it to three or four predefined alternative locations in and around each field.  In prior iterations a right-click had performed a different operation, so I was unaware of the change until I right-clicked expecting to trigger the previous action.

Of course its technique, implemented in only one extension, can only resolve conflicts between InformEnter+ and Kee (in my selfish instance), and does nothing to resolve conflicts between Kee and anything else.  Were you to follow InformEnter+'s example rather than declaring the conflict impractical to resolve, then every user of Kee and InformEnter+ would now have a solution, both together and independently.  I doubt that it is programmatically difficult to implement, as to my knowledge InformEnter+ also has a single lone developer.  Two extensions implementing the same solution to the problem also increases the possibility of it emerging as the collaborative standard you desire (I like standardization and collaboration myself).

Now go collaborate and start creating the de facto standard!

**Comment by zyphlar** [comment]
Came here after digging through the source code trying to figure out if it's possible to do this.
In my case, the website itself has a "show" button that sits in the right-hand side.

I'd almost prefer having the Kee button just sit on the left-hand side, either permanently or only for certain predefined domains. It's not like I'm ever going to have much need to click that far to the left since all my passwords are in Kee, and if I really need to type in there I can just click in the center and start typing.

I know it's possible to use the context menu, I just prefer the higher-quality Matched Logins menu instead.
