### ISSUE TITLE
Context menu should not be displayed on special pages

### ISSUE THREAD

**Issue by luckyrat** [kee-org/browser-addon#196]
E.g. New Tab page in Firefox, Extensions management page in Chrome.

Hopefully there's a straightforward part of the WE context menu API to enable this but I'm not sure so therefore not marking as a good first ticket.

**Comment by kapep** [comment]
There is the `documentUrlPatterns` parameter for [contextMenu.create](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create#Parameters) which restricts the menu to appear only on pages with matching URLs. If that's sufficient it should be quite straightforward.

Whitelisting only http and https schemes with that parameter would exclude the menu from all special pages. Are there any other schemes that should be matched?

**Comment by kapep** [comment]
You can define multiple patterns of which only one has to match, so I think `["http://*/*", "https://*/*"]` should work without including websocket URLs. I'll try this and submit a PR later.
