### ISSUE TITLE
[debian][bug] kee freeze quantum

### ISSUE THREAD

**Issue by nailyk-fr** [kee-org/browser-addon#206]
Hello, 

debian just switch his repo (firefox-esr package) to quantum so it is time to open https://github.com/kee-org/browser-addon/issues/27 back :)
Firefox just upgrade to quantum, so switch to kee. I had time to open an email, click forward, now the 'network part' of firefox is stuck. 

**Steps to reproduce:** 
Install firefox and keepass on your debian machine, install kee addon, browse 5 minutes. 
I think it should work without keepass. 

(mostly related to the issue I reported on mozilla bug tracker )

P.S.: I didn't check on the forum as this have been reported a while. 
P.S.2: If youd like, I can provide you a ready to crash virtual machine to test on your own. 
P.S.3: Thanks a lot! for having provided kee for such a long time, but it is a totally blocking issue (as firefox is not usable anymore) so testing on my side could be slow as I will need to move to another password storage solution in the time of fixing this issue.

**Comment by luckyrat** [comment]
What makes you think it is related to #27? That issue has been fixed for a long time.

What is the issue on Bugzilla?

Are you sure it's the network stack that's frozen?

A ready-to-crash VM is potentially useful but probably more so to the Firefox devs than to me. I have recently tried debugging a Firefox content process freeze bug on Ubuntu (no indication it has anything to do with Kee or any WebExtension - Linux I/O drivers of some kind are a possible culprit) and did not get very far at all - it looks like all public documentation on how to debug such issues is either absent or outdated. I created https://bugzilla.mozilla.org/show_bug.cgi?id=1504524 but it's not been triaged yet so I'm no more enlightened on what I could even do if I had access to a VM with a frozen content process (or network thread).

PS: In case it helps while Mozilla help us investigate the problem, Kee runs pretty well in Chromium now: https://chrome.google.com/webstore/detail/kee/mmhlniccooihdimnnjhamobppdhaolme?hl=en

**Comment by nailyk-fr** [comment]
Thanks for your fast answer! I agree it should be mozilla related as some other extensions are causing the same issue. 
About the linked issue, my memory probably cheated on me. Sorry. 
The issue your reported on bugzilla is mostly the same I had: (mostly this comment) https://bugzilla.mozilla.org/show_bug.cgi?id=1453706#c12
About the VM, looks like you already are able to produce the crash. I agree it is a pita as it happens randomly. I will try to produce one soon. 
Not sure about the 'network' stack being frozen, the only thing I can see is nothing loads anymore on firefox. I can do a tcpdump again, but from what I remember, no TCP packets gets out of Firefox process after this 'crash'. 

Sorry for not having more informations, but it happens randomly and I am definitively not a good developer :)

**Comment by nailyk-fr** [comment]
I cannot reproduce the issue except in Nightly with riot (matrix client) opened. 
Will reopen later if I can find something else.

**Comment by nailyk-fr** [comment]
As said in the mozilla issue ( https://bugzilla.mozilla.org/show_bug.cgi?id=1453706 ) I just received a new laptop, brand new ubuntu installation with Firefox 64.0, installed kee, opened matrix (https://riot.im) and the issue is there. 

I really don't know what to do, but it seems to be related to those 'infinite scroll' website (matrix/mastodon/pixelfeed/etc.)
After some time, all the 'network stack' of firefox is crashed. Only a close/open can solve it. 
As said, will try to provide you a VM with some dummy mastodon/matrix accounts into. 

Thanks all for your time!
