### ISSUE TITLE
Domain-only matching doesn't work

### ISSUE THREAD

**Issue by himselfv** [kee-org/browser-addon#210]
KeePass 1.40 standalone version, KeePassRPC 1.8.0.0, Kee 1.4.15, all downloaded from official pages. The only other plugin: "Entry templates for KeePass" 7.8.00

The default setting in "Database Settings" is domain URL matching (the top one). All the database entries in question also have "Domain URL matching" in their settings. But Kee behaves like it's hostname matching.

Say I try to login on "https://accounts.google.com". This is what matches and what doesn't:

https://accounts.google.com - matches
http://accounts.google.com - matches
https://google.com - doesn't match
https://test.accounts.google.com - doesn't match.
http://google.com - doesn't match

If I add "accounts.google.com" to the entry's "Kee > URLs > Additional URLs", it matches where it otherwise wouldn't. If I add just "google.com", it doesn't.

It totally looks like it's doing hostname matching, even though it's set to "Domain matching" everywhere.

Also (may be unrelated), in "Database Settings > Kee > Match accuracy > Domain overrides" when I click "Add" and literally just type "google.com" as in the example, it says "Invalid domain name". Other names don't work either.

**Comment by univert** [comment]
this seems to be a problem

**Comment by luckyrat** [comment]
Most likely relates to one or more of the issues already discussed on the forum: https://forum.kee.pm/t/kee-shows-a-lot-of-wrong-matches/1563

Please research and discuss further there and if we find something specific to address in the code we can create an issue here at that point.

**Comment by himselfv** [comment]
Yeah, it seems to had been the lack of publicSuffixDomainCache.txt file. Once I've created AppData\Roaming\KeePass folder it got automatically created there and domain-name matching works. Thanks!

Though I can't see any obvious reason why KeePassRPC would be unable to create that folder. Other apps write to AppData\Roaming just fine.
