### ISSUE TITLE
Generate Password Using "Automatically Generated Passwords" of Keepass

### ISSUE THREAD

**Issue by Johnex** [kee-org/browser-addon#211]
Hi!
I moved to the Kee plugin on chrome after using ChromeIPass for a couple of years now.
Kee is much better at finding login forms than ChromeIPass, but it lacks in the options to generate a password.

I would like to have the option to generate a password using the "Automatic Generated Passwords" that exists in Keepass. So if a site is not matched, add password generator icons to the fields like ChromeIPass does, and let the user apart from the strength as it is now, select the default password generation configured in Keepass. I also don't like that the password is saved into Keepass automatically. ChromeIPass only enters the password into the fields, and saves it to the clipboard. So you can give the user the option to save the password if they want, or let them manually paste it to an existing entry or a new one themselves.

When generating a password using the default, also add the bit strength like ChromeIPass does, or maybe even let the user select the minimum strength they want, and generate passwords until that matches. For example i usually click many times in ChromeIPass until i get a 20ch 130bit+ password.

**Comment by carlin-q-scott** [comment]
I'd really like to use the "Automatically Generated Passwords" that's user configurable in KeePass. I don't like the default options from Kee that are just hex strings.

**Comment by AlienSteel** [comment]
@Johnex My interpretations and follow up questions below as I am not sure what you´re asking for :-)
> I would like to have the option to generate a password using the "Automatic Generated Passwords" that exists in Keepass.

By right clicking and choosing Kee/Generate new password you can create a password using any of the profiles in KeePass except the "placeholder" ones (Custom) and (Automatically generated passwords for new entries), so it seems you have said option

>I also don't like that the password is saved into Keepass automatically.

There is a checkbox in the settings for Kee, not in the browser but in KeePass under "Tools/KeePassRPC (Kee) Options...", called "Store a backup of each password generated by Kee" I believe that if you uncheck that you would get the behavior you want. Unless you were referring to that a new entry is made when you post your login form on the site with the password that you typed and/or generated with KeePass, that might be what checking or unchecking the option Keeicon/Options/Saving entries/Offer to save passwords do, I haven't tested.

> So if a site is not matched, add password generator icons to the fields like ChromeIPass does, and let the user apart from the strength as it is now, select the default password generation configured in Keepass. I also don't like that the password is saved into Keepass automatically. ChromeIPass only enters the password into the fields, and saves it to the clipboard. So you can give the user the option to save the password if they want, or let them manually paste it to an existing entry or a new one themselves.

> When generating a password using the default, also add the bit strength like ChromeIPass does, or maybe even let the user select the minimum strength they want, and generate passwords until that matches. For example i usually click many times in ChromeIPass until i get a 20ch 130bit+ password.

Maybe I have to install and use ChromeIPass to see what you want but here goes my guess as to what you would like to see:

1. If Kee can not match a KeePass entry to the current webpage an icon was shown in the password field, similar to the icons that appear when a page is matched but maybe with an icon that leads the thought to generating a password.
2. When that icon is clicked a dialog would be shown similar to the one shown when choosing Kee/Generate new password in the context menu.
3. The dialog should give the user an option to chose which profile should be used to generate a password but selecting any option would not close the dialog nor autofill the password, nor copy the password to the clipboard
2. Changing the selection of Profile should generate a new password using that Profile but still not close, fill or copy the password
3. The user should be in control of when a generated password gets used: 
    1. as copied to clipboard, 
    2. to auto-fill fields,
    3. to be saved to a KeePass entry,
    4. to be backed up in KeePass.
    5. to update an existing KeePass entry.
4. A password generated by the Profile should be previewed in the form.
   1. The password should be shown either as dots or as viewable characters
   2. The passwords strength would be shown as number of bits
   3. (my addition) Optionally strength would also be shown as a colored bar

So basically an implementation that shows something like the "Edit Entry" dialog in KeePass but only with the "rows": Password:, Repeat: (optionally, if the dialog should also support manual entry of  a password, or say to modify an auto generated one) and Quality plus an OK button that would fill in the passwordfield, copy the password to clipboard and save the password as a backup in KeePass would do the trick?
Which actions Ok button does should be controllable in the Kee Options.

Or maybe clicking the icon would give two options, 1 as above 2 to open a new entry in KeePass in the EditEntry dialog with all fields filled as if one had posted the login form on the site, ie Title, User name etc but also detected fields in the form. 
In option 2 then the workprocess would be to click a field (and I guess this could be in any field really) in a login form for an unmatched website, choose the second option "Create Entry" maybe, save the entry after having all the possibilities in customizing password, user name etc, then saving the entry.
Back in the login form either automatically on saving the entry or after a page refresh the site would be recognized as a match and if configured autofill will be used and the user can add/change anything needed in the form and then post it, including doing reCaptchas or what not. If any fields were changed Kee would detect that and ask if the user want to update the KeePass entry.

Well that got a bit longer than I intended :-) but hope that this give you som help and maybe make your request more clear to any developer. I would personally like this to be fixed as well, I think I would actually prefer option 2 but an improved password dialog in Kee would be nice as well.

**Comment by AlienSteel** [comment]
> 
> 
> I'd really like to use the "Automatically Generated Passwords" that's user configurable in KeePass. I don't like the default options from Kee that are just hex strings.

Again not sure what you mean but if you want to be able to use the same settings when generation a password from Kee as the settings used for (Automatically generated passwords for new entries)?

Then all you need to do is select that in Password Generator and save it as a new profile, that new profile will be an option when generating new passwords in Kee as well as in KeePass.

Vice versa if you have a profile you'd like to use as the one automatically applied to new entries, configure or select a profile, press the save (disk) icon and in the dropdown select (Automatically generated passwords for new entries) then Ok, your profile will now be used for new entries.

**Comment by carlin-q-scott** [comment]
@AlienSteel Thank you for your response. I didn't realize that Kee provides access to all the password generator profiles in KeePass except the default one. I can save the default as something else so that it's accessible in Kee.

**Comment by AlienSteel** [comment]
You're welcome. That's right in a lot less words 😄
