### ISSUE TITLE
German non-formal version can be deleted

### ISSUE THREAD

**Issue by Siggi0904** [kee-org/browser-addon#225]
Hi Chris,

I updated the german translations for both projects in Transifex.
Now it's fully translated. Please merge it for next version.

In tutorial project you can delete the not translated de-DE language because a non formal language version is not needed, and actually not translated.

See: https://www.transifex.com/keefox/tutorial-addon-kee-pm/language/de_DE/

Thanks.

**Comment by luckyrat** [comment]
Hi,

Thanks for that. I've deleted de_DE now from the tutorial project and published the latest tutorial translations.

There might still be a few strings in the Kee project that will change before Kee v3.1 is pushed to the Beta testing channel so although I've just merged in the latest strings, I'll be doing that again fairly soon. You should see the usual notifications about new source strings from Transifex when I add or change the English source strings.

Thanks,
Chris

**Comment by Siggi0904** [comment]
ok, thanks and translation updated at transifex,
