### ISSUE TITLE
Kee icon with login options doesn't appear on USAA

### ISSUE THREAD

**Issue by angrycuban13** [kee-org/browser-addon#230]
Thanks for your interest in helping to improve Kee.

GitHub issues are for clear and well defined changes to project behaviour, appearance and code.

Issues may not always be worked on immediately but if there is not a clear plan and need for a change the issue may be closed, at least until the need or specification is more clearly evaluated on the community forum.

If you have not been asked to create an issue here and are unsure if creating an issue is the best way forward, please use https://forum.kee.pm instead.

In particular, please note that initial discussion regarding any of the following should begin on the forum:

* Help using Kee
* Documentation
* Bug reports
* Change proposals
* Feature requests
* Questions/comments about security(*)
* Help developing/building Kee

The full contribution and support guidelines can be found at: https://github.com/kee-org/browser-addon/blob/master/CONTRIBUTING.md

Thank you for following these guidelines - it will help us to keep each discussion focussed in a single place and improve the project more quickly.

(*) Note that sensitive issues should always be addressed via a private contact - see https://forum.kee.pm for how to do this.

When visiting USAA and trying to login the Kee icons don't appear on the login form for me to choose who to login as. 

![USAA](https://user-images.githubusercontent.com/39564898/57193989-dd03a000-6f06-11e9-92f4-f44e3f3e1bae.jpg)

I've tried multiple variations of the URL on the main entry as well as adding multiple domain URLs to the KeePass Kee URL entry but it just never allows me to pick a login. 

![URL](https://user-images.githubusercontent.com/39564898/57193988-dc6b0980-6f06-11e9-8f4d-59dc5eaf8651.jpg)

![Kee URLs](https://user-images.githubusercontent.com/39564898/57193986-dc6b0980-6f06-11e9-9578-5c996f8d0955.jpg)

Kee works with any other financial institution, so not sure if their login form is named a certain way that Kee doesn't recognize natively? I've attached two other financial institutions I usually access and I have no issues with Kee giving me login options

![BoFA](https://user-images.githubusercontent.com/39564898/57193985-dc6b0980-6f06-11e9-927f-104522b3188a.jpg)

![NFCU](https://user-images.githubusercontent.com/39564898/57193987-dc6b0980-6f06-11e9-849b-6ab53858ea22.jpg)

**Comment by luckyrat** [comment]
Thanks for your interest in helping to improve Kee.

GitHub issues are for clear and well defined changes to project behaviour, appearance and code.

Issues may not always be worked on immediately but if there is not a clear plan and need for a change the issue may be closed, at least until the need or specification is more clearly evaluated on the community forum.

If you have not been asked to create an issue here and are unsure if creating an issue is the best way forward, please use https://forum.kee.pm instead.

In particular, please note that initial discussion regarding any of the following should begin on the forum:

    Help using Kee
    Documentation
    Bug reports
    Change proposals
    Feature requests
    Questions/comments about security(*)
    Help developing/building Kee

The full contribution and support guidelines can be found at: https://github.com/kee-org/browser-addon/blob/master/CONTRIBUTING.md

Thank you for following these guidelines - it will help us to keep each discussion focussed in a single place and improve the project more quickly.

(*) Note that sensitive issues should always be addressed via a private contact - see https://forum.kee.pm for how to do this.
