### ISSUE TITLE
Add option to take into account URL scheme when matching entries

### ISSUE THREAD

**Issue by PlqnK** [kee-org/browser-addon#235]
Hi!
First of all thank you for your work on this add-on, it's great!

I would like to propose to add another level to the `Minimum URL match accuracy` setting between `Hostname` and `Exact` that would be like the hostname one but take the URL scheme into account.

The reason is that when I use the `Hostname` setting, Kee returns entries that I don't want, for example:

What's in my database
![2019-05-10 08_51_15-ESYS-INFRA kdbx - KeePass](https://user-images.githubusercontent.com/3833277/57508812-e4f68200-7302-11e9-8bd8-0283c0dea717.png)

What shows in my browser
![2019-05-10 08_51_27-ManageIQ_ Login - Firefox Developer Edition](https://user-images.githubusercontent.com/3833277/57508815-e88a0900-7302-11e9-8efa-d1a17214ceee.png)

And the `Exact` setting is to much for my usage, some websites I use have the SAML request token in the URL like `https://sub.domain.tld/SAML2?SAMLRequest=<token_here>`, which changes each time I try to log in so Kee doesn't match my entry that only have `https://sub.domain.tld/SAML2` in it's entry URL field.

**Comment by luckyrat** [comment]
Use a Regex, or hide the SSH entries from Kee.

Please use the forum in future for questions/discussion: https://forum.kee.pm
