### ISSUE TITLE
Make the form whitelist and blacklist case-insensitive

### ISSUE THREAD

**Issue by luckyrat** [kee-org/browser-addon#237]
In most situations it makes sense for the strings used to decide if a form should be whitelisted or blacklisted to be case-insensitive. Since some existing user configurations could depend upon the current case-sensitivity, we need to offer a general and site-specific opt-out from the new behaviour.

Implement by adding a new default true site-specific setting to the config structure and settings page - "Ignore case". Then conditionally apply toLowerCase() on all the comparisons in ConfigManager.isFormInteresting()

I'm assigning to myself due to ongoing refactoring that could impact this work but won't be implementing it immediately so I can re-assign if anyone else particularly wants to implement it urgently.

**Comment by levicki** [comment]
If I may suggest, it might be better to allow regex in those strings and let users express desired case-sensitivity through regex.
