### ISSUE TITLE
Allow searching for passwords

### ISSUE THREAD

**Issue by chris246** [kee-org/browser-addon#238]
(Re)Add the search field to allow searching the suggested entries list that shows after focusing an input field.

Imho searching for a username would be most beneficial.

**Comment by chris246** [comment]
See also #7

**Comment by luckyrat** [comment]
I'm not sure what this relates to but as far as I can tell it's no longer relevant. Feel free to search and discuss on the forum if you have further information to add: https://forum.kee.pm
