### ISSUE TITLE
Authorization tab not appearing (when no window is present)

### ISSUE THREAD

**Issue by elieux** [kee-org/browser-addon#243]
This might be something weird on my part or an interesting edge case.  Seems like when there's no Chrome window open (but the profile is somehow active in the background), Kee tries to authorize with KeePass, but doesn't open any authorization tab, so it looks like the requests are coming from nowhere.  Exiting Chrome completely and starting it again with a visible window allowed the authorization process to continue normally.

> Chromium v74.0.3729.169 (Official Build) (64-bit)
> Kee v3.2.7

**Comment by luckyrat** [comment]
I've not been able to reproduce this but I have made some small changes to Kee 3.6 which should increase the chances that this authorisation tab will be brought to the front and made visible by Chrome. Perhaps there is even more that we can do if v3.6 doesn't help but ultimately it'll be hard to test this thoroughly without a reliable way to reproduce the exact "running but not really" state of Chromium that prompted the initial creation of this issue.

We can keep this open for a while after the release of v3.6 to see if it helps or not.

**Comment by elieux** [comment]
I don't think I've observed the issue more than once, so maybe we can close. I'll post an update if it shows up again.
