### ISSUE TITLE
FindLogins suddenly changed behavior and started returning additional matches

### ISSUE THREAD

**Issue by vbojan** [kee-org/browser-addon#244]
I have 2 similar entries:
1. URL=https://aaa.example.com and no URL configuration for Kee (shows Domain as default).
2. URL=https://bbb.example.com and URL configuration for Kee: Domain, Normal, Match for https://ccc.example.com

Ever since I've used Kee(Fox), if I go to https://aaa.example.com it would only offer entry #1 whereas if I go to either https://bbb.example.com or https://ccc.example.com it would only offer entry #2.

However, yesterday out of blue, it started returning both entries for either URL I visit.
I have multiple similar pairs or triplets where I have different credentials for different subdomains - they were all configured and behaved in the same way and all changed behavior yesterday.

After reading more carefully the description for each option under URL tab, it feels more like it was behaving incorrectly before and now suddenly behaves as it should as both entries have Domain set. But it behaved as desired for a very long time and I didn't question what obviously didn't feel right.

Even though it defaults to Domain, based on behavior it looks like it was doing Hostname match as even with Domain selected I had to explicitly add https://aaa.example.com, https://bbb.example.com and https://ccc.example.com to make them work with default URL https://www.example.com and use the same credentials.

I completely restored the Firefox profile and full KeePass with DB and configuration from the last week when I know all this was 100% working as expected, aside if Domain configuration was correct or not. but it still behaves differently than 2 days ago.

I'm using KeePass 2.43 with Kee 3.2.7, KeePassRPC 1.9, Firefox x64 70.0.1 on Windows x64 7 Pro SP1.
All versions were updated on the day of the release so besides Firefox update ~2 weeks ago KeePass and its plugins/configuration haven't changed for months.

The only thing that did change over the last few days is that I installed these updates yesterday: KB4523206, KB4525235, KB4484160, KB4484127 and KB4484164.
It feels as this shouldn't matter, but as that's the only recent environment change and was made right before this behavior changed it might be related.

If I change Minimum URL match accuracy to Hostname everything works fine but I still can't remove those additional subdomains aaa.* bbb.*... as it still doesn't recognizes the domain properly in accordance to the description.

**Comment by vbojan** [comment]
I did some more investigation and found that KB4523206 had status "Pending" and had no way to fix it. Trying to reinstall it was showing a message it was already installed.
So I did system restore and installed all updates. This time it was successful and Kee is working the same as before which makes me believe KB4523206 didn't install properly the first time and somehow affected Kee's behavior.

That "Domain" option under URL tab is still confusing me though and I checked KPRPC JSON details and found all entries to have both blockHostnameOnlyMatch and blockDomainOnlyMatch set to false.

**Comment by luckyrat** [comment]
Sounds like TLD data couldn't be accessed until very recently. Maybe a windows update since the restore point fixed some broken file system permissions or a firewall configuration was changed. Or maybe that dodgy update broke your corporate policy or a firewall configuration that was previously preventing Kee from working correctly?

https://forum.kee.pm/t/problems-when-keepass-cant-determine-a-domain-name-using-the-psl/2346 will give you more context if you wish to continue investigating.
