### ISSUE TITLE
Kee Autofill dont workin at postbank.de

### ISSUE THREAD

**Issue by it-consult** [kee-org/browser-addon#245]
on https://meine.postbank.de/#/login i can not use autofill, but only Username, Passwort (at second page) worked without any problems.
I tried to add "postbankid" to whitelist but without success.

What ist wrong with this page?
What cann i do to resolve this problem?

Newest Firefox (70.0.1)
Newest Kee Plugin (3.2.7)
Newest KeePassRPC (1.10.0.0)

**Comment by luckyrat** [comment]
Please search and post on the community forum rather than here. https://forum.kee.pm

**Comment by Grocel** [comment]
The forum has no results on that. It is a common problem. I have some debug logs on this:

```
scanForOrphanedFields took: 0 common.js:formatted:67
Finding matches in a document. readyState: complete common.js:formatted:76
findMatches processing 1 forms common.js:formatted:67
about to get form fields common.js:formatted:67
processing field with domtype text... common.js:formatted:67
usernameIndex: -1 common.js:formatted:67
actualUsernameIndex: 0 common.js:formatted:67
otherFields.length:1 common.js:formatted:67
No password field found in this form and either there are no other fields or no whitelisted text field or form element
```

The form in the bank website has no password field on the first page, because it is on the 2nd page. Is it possible to configure the extension to fill out the user field without having a password field?
