### ISSUE TITLE
Selectively pre-empt autosubmit when using secondary accounts

### ISSUE THREAD

**Issue by detuur** [kee-org/browser-addon#246]
Hi,

Using the Kee extension is generally smooth sailing, but I'm encountering an annoying issue with autosubmit behaviour on websites with more than one account. I'll explain briefly:

- **Environment**: Website has two accounts: one primary, one secondary. Primary account is used so often, and has to log in so many times per day and per session (due to auto logout) that it's configured to autosubmit. The secondary account has a lower priority set than the primary so that primary can autofill without issue.

- **Scenario A**: The default scenario. I access the website through a bookmark to my accounts dashboard, I get redirected to the login page, Kee autofills my default credentials and autosubmits, and I land on the intended page. 2 seconds total. Everything behaves as expected.

- **Scenario B**: Rarely, I need the secondary account. Since going through the bookmark is not an option due to the behaviour of Scenario A, I instead click the Kee extension button in my browser, search for the secondary account entry, and click it.
    - **Expected behaviour**: The login page opens, but instead of autofilling the primary account data, it autofills the secondary account data, allowing me to click the login button and submit the secondary credentials.
    - **Actual behaviour**: The login page opens, but the primary account data is autofilled _and_ autosubmitted, giving me no chance to use my secondary credentials. I have to go into KeePass to turn off autosubmit for the other account in order to log in.

- **Proposed solution**: When using the Kee extension menu search, disable autofill and autosubmit for all other matching entries.

- **Other notes**: In the KeePass property dialog for entries, under the Kee tab, you can turn autosubmit to either "enabled", "disabled", or "use Kee setting". It would be nice if this could be extended with "direct links only" or some other phrasing, that would only enable autosubmit after clicking an entry in the extension's search box.

**Comment by luckyrat** [comment]
I think your scenarios are similar to those being discussed in the community forum and thus some of the planned solutions I proposed in https://forum.kee.pm/t/prioritising-and-sorting-matched-entries-in-kee-3-5-and-higher/3112/24?u=luckyrat should help. Please continue discussion on the forum if you have anything to add to that discussion or create a new topic with your updated thoughts now that Kee 3.5 has been released.
