### ISSUE TITLE
Error in /lib/tp/browser-polyfill.min.js

### ISSUE THREAD

**Issue by CharlesDelorme** [kee-org/browser-addon#248]
There is a console error triggered by this library (sorry for the link in french) : 
"
Erreur dans les liens source : TypeError: NetworkError when attempting to fetch resource.
URL de la ressource : moz-extension://f308ec7e-b570-4c34-a303-b1209a823ba8/lib/tp/browser-polyfill.min.js
URL du lien source : browser-polyfill.min.js.map
 "

Solution is given in this thread : https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/187 . It seems it only needs to remove one line 
"
Easy fix:
Please remove the line //# sourceMappingURL=browser-polyfill.min.js.map in browser-polyfill.min.js.
"

**Comment by Xeevis** [comment]
+1, extension is cluttering console with 404 http errors on every page. Either remove the reference for the source map file, or bundle the source map file with the extension.

**Comment by Alldar** [comment]
Please fix this warning. Every time I see this in a console, it is incredibly annoying. :)
Thanks for your work!

**Comment by luckyrat** [comment]
Unfortunately Mozilla require that this file is used without modification and therefore we just have to put up with the source map warning messages.

If they ever change their policy I will be glad to reintroduce the "fixed" version that I used in earlier versions of Kee.
