### ISSUE TITLE
Little icons are not clickable on some sites

### ISSUE THREAD

**Issue by develguebil** [kee-org/browser-addon#251]
The little icons are not clickable on some sites due to the "show password" icon overlapping for example:
 https://mail.protonmail.com/login
It's not a major issue but it is annoying

**Comment by luckyrat** [comment]
That's a known problem with a handful of sites and there is no known way to avoid it. It's probably already discussed on the [community forum](https://forum.kee.pm) if you want to continue the discussion there.

Workaround is to use the main popup instead.

Looks like Protonmail have fixed the problem on their beta website anyway.
