### ISSUE TITLE
Kee evertime asks for authorization

### ISSUE THREAD

**Issue by JDrillz** [kee-org/browser-addon#254]
Hello, I'm having an annoying issue with Kee (last version).
Everytime I reopen Firefox, it asks me the authorization code. Only on my notebook, not on my desktop, both with W10.
I already tried to reinstall FFX, Keepass and Keefox, what can I do to solve?

Thanks

**Comment by tomwiggers** [comment]
If you are talking about basic authentication prompts, then me too. There is a bug somewhere that if Firefox (it happens to me in FF, haven't tried other browsers), is set to reopen your tabs on launch, and you had a tab open that requires HTTP basic authentication, the Kee Vault browser plugin will keep opening prompt infinitelely until you manage to click  a login in one of the windows. I have attached a screenshot.
![2020-03-01 15_20_56-](https://user-images.githubusercontent.com/17702902/75629695-66960400-5be4-11ea-83bb-08cc6277f0be.png)

**Comment by JDrillz** [comment]
Hello, no, I'm talking about this:
[url=https://ibb.co/6m79Hz4][img]https://i.ibb.co/6m79Hz4/Cattura.jpg[/img][/url]
(screenshot isn't mine)

It appears everytime I reopen Firefox, but on my notebook only, not on my desktop.

**Comment by tomwiggers** [comment]
Ah okay. I will open a seperate issue then.

**Comment by rjt** [comment]
If you happen to have two databases open in the KeePass application on your notebook, check to make sure there are different names in the "File" --> "Database Settings" -->  "Database name:" fields.

**Comment by JDrillz** [comment]
Thanks for you answer, I have only one database

**Comment by luckyrat** [comment]
Please check the troubleshooting information on the forum and search for other information there: https://forum.kee.pm/t/troubleshooting/560#heading--enter-password-every-time
