### ISSUE TITLE
Configure site-specific completion settings

### ISSUE THREAD

**Issue by Yamakaky** [kee-org/browser-addon#257]
The Kee extension allows the user to configure if the form should be submitted or not after completion for all the sites, but not for one specific. I would like to disable the auto-submit for a specific site.

**Comment by luckyrat** [comment]
You can override this setting for each relevant entry rather than for individual sites. Anyway, if you want to provide some more information or contribute to similar discussions, this is what the (community forum)[https://forum.kee.pm] is for, rather than this code issues tracker.
