### ISSUE TITLE
Kee cannot distinguish between create account and login pages at gmail.com

### ISSUE THREAD

**Issue by levicki** [kee-org/browser-addon#258]
When I try to register a new email account at gmail.com and enter first name, last name, and desired email and then open password database (KeePass) to generate new password, Kee overwrites fileds on the registration form which were already filled manually.

In doing so, it fills in an existing login email to First Name field, and existing password to both password fields. All registration fields are displaying Kee icons.

I hope this can be improved soon or I will have to find some other, smarter addon.

**Comment by luckyrat** [comment]
Kee has a check to ensure it doesn't overwrite existing data. If this issue is still relevant in Kee 3.5, feel free to search and discuss on the forum so we can determine how best to help: https://forum.kee.pm
