### ISSUE TITLE
Add Kee to the Microsoft Edge extension store

### ISSUE THREAD

**Issue by Buxingke** [kee-org/browser-addon#260]
Since the new Microsoft Edge is based on chromium, the addon can be easily move to the Microsoft Edge extension store for convenient upgrade. Thanks for the nice work.

**Comment by luckyrat** [comment]
The process looks quite involved and expensive but I will give it a try as part of the Kee 3.6 release soon.

**Comment by luckyrat** [comment]
https://microsoftedge.microsoft.com/addons/detail/kee-password-manager/amfjccmjojpjginicahekljnhhjemjec

**Comment by henriquegemignani** [comment]
It'd be very nice to have https://www.kee.pm/ link to that page as well, as a way of confirming that download offering is trustworthy.
