### ISSUE TITLE
Dereference {REF: to their username and passwords

### ISSUE THREAD

**Issue by SantosSi** [kee-org/browser-addon#262]
In KeePass I have entries referring the username and password to another entry. In the Firefox Kee addon 3.2.7 the reference code ({REF: ...) is entered as the user name and probably also as the password respectively instead of the user name and password it refers to.

**Comment by ksoellin** [comment]
Hi,

I ran into the same problem, but found out that this is the desired behavior (s. [Placeholder handling](https://forum.kee.pm/t/placeholder-handling/1100)).
To use those references you have to actively enable `KeePass placeholders` in your "Database Settings"  under "Kee" and than "KeePass placeholder". To be complete, please mind the warnings.
