### ISSUE TITLE
Priority Override configuration is being ignored in the latest version

### ISSUE THREAD

**Issue by vbojan** [kee-org/browser-addon#272]
Just upgraded to Kee 3.5.19 and immediately noticed something is wrong with configured Priority overrides that worked perfectly in the previous Firefox version of Kee 3.2.7 (Firefox 79.0 x64 on Windows 7/10 x64).

I tried searching for any changes, bugs or discussion related to priorities but found nothing recent. except a comment in this file:
https://github.com/kee-org/browser-addon/blob/08f251c44ab2120adb4448d5b716ed4b08048a65/page/formFilling.ts
at line #1604:
`// Kee 3.4+ no longer considers priority overrides because they were`
`// complicated and unreliable even when fully understood.`

I hope it was not intentional to completely kill this functionality as the related configuration is till showing up under Kee tab for each KeePass entry.

Here's the issue I'm having because of whatever was changed here.
I have multiple accounts for various websites (i.e. regular user, special user, content admin, system admin etc.) and I have them ordered in certain way by using Priority Override so when visiting a matching URL Kee shows them in custom sequence like this:
user1 - App X [Sys Admin]
user2 - App X [Content Admin]
user3 - App X [Primary User Account]
user4 - App X [Secondary User Account]
user5 - App X [Alternate User Account]

However, Kee 3.5.19 appears to ignore existing configuration and no matter how I tried to reconfigure priority overrides it keeps showing the list using alphabetical sort for entry titles so they look like this:
user5 - App X [Alternate User Account]
user2 - App X [Content Admin]
user3 - App X [Primary User Account]
user4 - App X [Secondary User Account]
user1 - App X [Sys Admin]

Right now the only way to get back the desired list sequence is to put 01, 02, 03, 04,... 10, 11 numbered prefixed into each entry title in front of brackets :(

Speaking of overrides, would't it be better to store Kee configuration into KeePass like form overrides, white lists and black lists? That way all configuration would be in one place instead of configuring each browser instance being used with Kee.

**Comment by pasbec** [comment]
It defnitely was [intentional](https://forum.kee.pm/t/priority-override-in-wrong-sort-order/3112/3) and the developers don't seem to care AT ALL. They are instead proud of some crappy match scores and a fency new search feature to allow you to search for something that you already know where it is.

**Comment by mberger-git** [comment]
Affects me too. Priority was working for me and did exactly what it should.

**Comment by luckyrat** [comment]
Please let's keep discussion about this topic in the one place on the community forum to save duplication and confusion :-)

https://forum.kee.pm/t/priority-override-in-wrong-sort-order/3112/
