### ISSUE TITLE
Inifinite "authorise a new account" windows

### ISSUE THREAD

**Issue by gglt** [kee-org/browser-addon#278]
I am running Ubuntu 20.04 on my personnal PC with Firefox 81.0 and Chromium 85.0.4183.121.

I have a personnal account and a professional one. The problem appears when I use both accounts togethers.
On one hand, I have my personnal session opend with my personnal keepass database opened. On the other hand, I have my professionnal session opened with my professional keepass database opened. On both linux sessions, I get an infinite "authorise a new account" window to link keepass with the browser of the other session.

I do not understand why kee in one session can reach keepass in the other session. I insiste, I use 2 differents linux sessions.

**Comment by luckyrat** [comment]
This has been asked and answered many times before. Please search and post on the community forum rather than here. https://forum.kee.pm
