### ISSUE TITLE
URL Field by reference {REF:} is not resolved while comparing URL with website

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [kee-org/browser-addon#284]
No matching of Entries using URL Field by reference {REF:} is not resolved while comparing URL with website.
Why? Because you may use multiple Account for single login page. most common work/private.
But while reduce redundancy in database where possible and for better allowing of changes.

Browser add-on should offer filling of entry that uses referenced Fields.
Any entry with referenced URL is not found or offered for login.
Consider resolve References in URL field of entries while matching URI.

Reproduce
create a entry.
Make sure kee-browser-addon lets you log in into website
duplicate entry and choose for the duplicate entry URL FIELD the original entry URL FIELD as reference
navigate to website, don't find the newly duplicate entry.

Kee - Password Manager
Version
3.5.20

keepass 2.46

browser chrome Version 86.0.4240.75 &firefox latest

**Comment by luckyrat** [comment]
I think this would be too risky but feel free to discuss on the forum to see what other people think of the idea: https://forum.kee.pm
