### ISSUE TITLE
Scrolling required to save credentials to existing KDBX in Firefox 82 x64 under Windows 10 on a 4K screen with 150% scaling in Kee v. 3.5.20

### ISSUE THREAD

**Issue by victorroth** [kee-org/browser-addon#287]
My setup:
Firefox 82 x64 rolling release
Kee, v. 3.5.20
Windows 10 Education, v. 2004
4K screen with 150% scaling enabled

When adding new credentials to my KeePass store through Kee, I have to scroll down to save to an existing KDBX. It took me 5 minutes to figure out why I could not save data. I can imagine that this is a bigger issue for inexperienced users.

<img width="331" alt="kee_scrollbug" src="https://user-images.githubusercontent.com/13812255/97078713-39bcb400-15ee-11eb-919d-184afd3770a6.PNG">
)

**Comment by luckyrat** [comment]
Please have discussions on the community forum, rather than here.

https://forum.kee.pm/t/kee-3-5-released-feedback/3073 makes a similar point I think, although I didn't really understand all of it so after reading it you may prefer to start a more focussed topic and reference that one.
