### ISSUE TITLE
Fill password fields last

### ISSUE THREAD

**Issue by luckyrat** [kee-org/browser-addon#288]
We've found an example of a buggy website which deletes the contents of the password field after the username field is filled in.

Since it would be an easy change, and easy to change back if beta testing suggests it's necessary, and because username fields are typically thought of as coming "before" password fields, we should swap the order that fields get filled.

See https://forum.kee.pm/t/cant-auto-fill-password-on-the-website-https-passport-bilibili-com-login/742

**Comment by Jay-Aware02** [comment]
Can I help?
