### ISSUE TITLE
Filling in Passwords on different ports/different subdomains (KeePass)

### ISSUE THREAD

**Issue by Kruemmelspalter** [kee-org/browser-addon#292]
I have a small homelab with two services requiring passwords/authorization. They run on different ports but on the same host. If I just use `<host>:<port>/` in KeePass as URL, the Add-On suggests both passwords/usernames on both ports.

**Comment by Kruemmelspalter** [comment]
There's also a Reddit post:https://www.reddit.com/r/KeePass/comments/jmyadv/portsubdomain_specific_url_entry_for_keepassrpckee

**Comment by luckyrat** [comment]
Please search and discuss on the community forum so we can determine how best to help: https://forum.kee.pm
