### ISSUE TITLE
One related account, two different credentials

### ISSUE THREAD

**Issue by thethinker990** [kee-org/browser-addon#294]
Feature-Request:

Abstrakt:
I have a account with standard credentials (username + password) and it's like SSO, I got that credentials on many sites. But one of the sites has different credentials, but it's part of this system. I can set up the different _username_ with the _form fields_ feature and custom _string fields_ but with the password field I can not. Problem is the same _Id_ of the password field.

Requested feature:
A fourth field like _Id_ for additional URLs or any other marker like _type_, _name_, _class_, _div class_ but with the URL I think it would be the best option.

I know, one could create another entry for KeePass but it's related and belongs to this account. I had to change things on two entrys every time and that would probably fuck up my safe.

**Comment by luckyrat** [comment]
Please use the community forum to discuss feature requests and the use cases for the feature.

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
