### ISSUE TITLE
Kee for Chrome is not working with Drupal sites

### ISSUE THREAD

**Issue by grzegorz-pietrzak-droptica** [kee-org/browser-addon#297]
Hi, the latest version causes problems on some sites based on Drupal. Please see the example: https://handytools.pro/user/login

When I visit if from two different machines that use common .kbdx file (Chrome@Ubuntu and Chrome@Windows), the credentials for this url are not detected. Instead, I get 34 errors in the console:

```
Error in event handler: TypeError: _b.toLowerCase is not a function
    at ConfigManager.isFormInteresting (<URL>)
    at FormFilling.findMatchesInThisFrame (<URL>)
    at <URL>
login:1 Error in event handler: TypeError: _b.toLowerCase is not a function
    at ConfigManager.isFormInteresting (chrome-extension://mmhlniccooihdimnnjhamobppdhaolme/common/common.js:16:25441)
    at FormFilling.findMatchesInThisFrame (chrome-extension://mmhlniccooihdimnnjhamobppdhaolme/page/page.js:1:18829)
    at chrome-extension://mmhlniccooihdimnnjhamobppdhaolme/page/page.js:1:55177
```
This happens for Drupal 7, Drupal 8 and Drupal 9, so it means millions of sites.

**Comment by NecatiMeral** [comment]
I've experiences this particular error too on a Joomla!-site.

**Comment by kapdap** [comment]
Also experiencing this issue on non-Drupal sites. Produces high CPU load.

**Comment by kapdap** [comment]
https://github.com/kee-org/browser-addon/blob/7c86f65fcfc5ceec3355bccf160d2a4bf428f801/common/ConfigManager.ts#L580

Null check is being used here. Chrome seems to return an empty string instead of null if the "name" value is not set.

**Comment by sebthom** [comment]
I am seeing the same error with [ActiveMQ Artemis Admin UI](https://activemq.apache.org/components/artemis/documentation/latest/management-console.html) on Chrome which is based on hawt.io and AngularJS afaik.

**Comment by burtek** [comment]
Same issue happening for me. @kapdap the issue is that `form.name` can resolve to an `input` with `name="name"` that sits in the `form` - that's the issue with https://login.wyborcza.pl/ (among others). This really needs to get fixed.

Ideally, rather thatn doing `form.id` or `form.name`, `form.getAttribute('id')` etc should be used.
