### ISSUE TITLE
#KeeAddonPanelMatchedLogins not at the top

### ISSUE THREAD

**Issue by sylingd** [kee-org/browser-addon#30]
For example, in this page: [Baidu Tongji](https://tongji.baidu.com/web/welcome/login), click the "登录" on the top right
![2017-09-18_124158](https://user-images.githubusercontent.com/5326684/30529314-ce4f49ea-9c6e-11e7-80cb-ba2dc5c17a3a.png)

then, the login form is displayed as a modal dialog, but the dialog to select my user is not at the top
![2017-09-18_123859](https://user-images.githubusercontent.com/5326684/30529302-b3acbda2-9c6e-11e7-871d-7896e7263f61.png)

Set the "z-index" for #KeeAddonPanelMatchedLogins to a large number, it works well

**Comment by luckyrat** [comment]
Thanks for reporting the problem. The z-index was not being set correctly but in the next release it will be.
