### ISSUE TITLE
plugin doesn't appear to be resolving {REF:} correctly any more?

### ISSUE THREAD

**Issue by mrforsythexeter** [kee-org/browser-addon#301]
In stead of completing the resolution of entries which refer to other entries, its just putting the reference in now?

![image](https://user-images.githubusercontent.com/1302231/105975206-9a90d800-6086-11eb-95bf-cb5814a2b6f5.png)

If I auto type from KeePass, it completes as expected, which tells me that it can resolve the lookup.

Version 3.6.27
Browser Firefox

**Comment by dlech** [comment]
Duplicate of #181?

**Comment by mrforsythexeter** [comment]
I agree
