### ISSUE TITLE
[Edge Browser] The Kee extension is disabling Edge's ability to save passwords to the browser's own password store.

### ISSUE THREAD

**Issue by ned-martin** [kee-org/browser-addon#309]
Edge Browser:

The Kee extension is disabling Edge's ability to save passwords to the browser's own password store.

The **Offer to save passwords** option in Edge Browser is disabled, and says "Go to Kee - Password Manager settings to change this", however there does not appear to be any way to enable this via Kee either.

It appears that installing the Kee extension breaks/disables the browser's ability to store passwords.

**Comment by ildar** [comment]
same for the Firefox.
I suggest this behavior should be optional.

**Comment by ned-martin** [comment]
You can force Firefox to save passwords even with Kee installed. See https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig and use `lockPref("signon.rememberSignons", true);`

However I agree, the proper solution is for the Kee addon to allow this. I'm quite surprised it doesn't. Clearly the author has decided most people should not use both the browser's password storage, and Kee at the same time, however I think this is an arrogant decision that doesn't take into account the many people (such as myself) who need to use it this way. 

The solution is for Kee to default to setting this option as it currently does, but to provide a method for advanced users to change this so that the browser's inbuilt password store can still be used.

**Comment by luckyrat** [comment]
The latest on this topic is https://forum.kee.pm/t/kee-has-disabled-the-browsers-inbuilt-ability-to-save-passwords/3968/4

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
