### ISSUE TITLE
Active tab not detected at startup in Firefox

### ISSUE THREAD

**Issue by luckyrat** [kee-org/browser-addon#31]
Works fine in Chrome.

Possibly because https://bugzilla.mozilla.org/show_bug.cgi?id=1342207 only addressed the case where Firefox is already running and a new window opens but a session restoration at startup seems to not trigger browser.tabs.onActivated

I'm investigating if there is a way to workaround this problem.

**Comment by gojpdchx** [comment]
I can confirm this with the use of Kee 2.0.0 alpha8 and latest Firefox Nightly.
A temporary "solution" is to open `about:addons`, followed by a force reload of Kee - click disable and then enable Kee again.

**Comment by luckyrat** [comment]
@gojpdchx Please can you supply some more information about what behaviour you see? Do you have any debug logs from the browser console that might help us identify what's happening?

I thought alpha8 might work around the problem where the active tab was not detected and it seems to work correctly in my test and live environments so you may be experiencing a different problem?

**Comment by gojpdchx** [comment]
@luckyrat 

On further testing, I make sure that other addons are disabled and investigate Kee's behavior. In all test cases, I already have my KeePass program opened and make sure that Kee is connected to the database, i.e. not displaying "OFF", before doing other steps.
My browser is set to open one `about:home` tab on startup and on new tab pages. This tab will be referred to as "Tab A" below.

The first test case is I would like to use Kee on Tab A.
If I do not wait for at least 20 seconds before going to a webpage on Tab A, Kee will not function on that tab.
Conversely, If I wait for 20 (or 25) seconds, then go to a webpage on Tab A, Kee will function normally on that tab.

The second test case is not to use Tab A. Instead, I open a new tab "Tab B".
Once Tab B is opened, go to a webpage. No matter Tab A is closed or not, Kee will function normally on Tab B.

The third test case is that I want to use Tab A, but is not willing to wait for 20 seconds before I can use Kee on Tab A.
First, I open a new tab "Tab B" and switch to it. There is no need to go to any webpage on Tab B.
Then, I switch back to Tab A and go to a webpage. Kee will function normally on that tab.

My conclusion is that I have to either:
1. Wait for 20 seconds to use Kee
2. Switch tabs

**Comment by luckyrat** [comment]
@gojpdchx That's interesting. I would expect 5 seconds, or maybe 10 on a very slow computer as a result of another Firefox bug I've worked around in 5 second periods but 20 is a bit too high for me to think that's definitely related.

Can you try a variant of the third test case but change focus to a different program on your computer (e.g. KeePass) and then back to Firefox, all why remaining on Tab A. Does that fix up the issue in the same way as if you'd opened a Tab B?

**Comment by gojpdchx** [comment]
@luckyrat 
Following your suggestion, this time I opened Firefox and then immediately switched to another program. (I used KeePass for this purpose.) When I went to a website on Tab A, Kee would function normally. Just as what you have said, switching focus to another program fixed up the issue the same way as if I'd opened a Tab B.

**Comment by luckyrat** [comment]
https://github.com/kee-org/browser-addon/releases/tag/2.0.0-a12 has another possible workaround for this bug

**Comment by gojpdchx** [comment]
@luckyrat 
I would say the problem seems to be partially fixed in alpha 12.
I can remain on Tab A, but instead of changing the focus to another program, I have to manually click "Find matching logins" in the context menu.

**Comment by luckyrat** [comment]
@gojpdchx That's good news. The need to manually ask to find logins is a separate issue to this which I fixed in alpha 13: https://github.com/kee-org/browser-addon/releases/tag/2.0.0-a13

**Comment by gojpdchx** [comment]
@luckyrat 
Alpha 13 fixed this issue for me. Thanks!

**Comment by luckyrat** [comment]
Sounds like this was fixed so closing now.
