### ISSUE TITLE
isFormInteresting fails to ignore case for include list items

### ISSUE THREAD

**Issue by luckyrat** [kee-org/browser-addon#313]
The `ConfigManager.isFormInteresting` method only reliably ignores case for exclude list items. While that does solve a lot of the problems the "ignore case" feature set out to resolve, the user interface implies and in my opinion user expectation would be that the setting applies to the include list too.

A map/filter operation needs to be performed on the 4 include* arrays similar to the exclude* equivalents.

Until merged and released, users can work around this bug by disabling the "ignore case" feature and ensuring that they type the exact ID or name into the include (and exclude) lists.

**Comment by Michaelsy** [comment]
> **for common German Postbank**
> **Pls can you provide exact settings**

![Screenshot](https://user-images.githubusercontent.com/38754074/178205527-e7e018b4-42cf-4b06-bd54-446aeafb2f2f.png)

\- Michael Sy.

**Comment by luckyrat** [comment]
Will be fixed in Kee 3.11.
