### ISSUE TITLE
"unknown URL" after update latest version

### ISSUE THREAD

**Issue by antys10g** [kee-org/browser-addon#315]
Hi,

After update from some old version of "Kee - Password Manager" to latest version
![obraz](https://user-images.githubusercontent.com/16255998/149598246-7a4dae15-1720-4539-a9fe-70dfa9469d6c.png)
"Kee generated password" entities have unknown URL instead of actual urls:

![obraz](https://user-images.githubusercontent.com/16255998/149598460-8bdd3556-2a73-4d89-a82c-19450f36ece6.png)

Settings:

![obraz](https://user-images.githubusercontent.com/16255998/149598073-aaded22d-ec11-4061-96bc-939ddbd1a6fe.png)

![obraz](https://user-images.githubusercontent.com/16255998/149598421-e4d3aaaa-c3b2-46f6-a4b9-47263aaf9946.png)

**Comment by luckyrat** [comment]
I can't reproduce this behaviour with Kee 3.11 and KeePassRPC 1.15 (haven't tested with earlier versions). When 3.11 is released please try again and if you still have trouble, let us know on the community forum and include steps to reproduce the issue so we can investigate further.

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
