### ISSUE TITLE
[Enhancement] Keyboard controls in the HTTP AUTH window

### ISSUE THREAD

**Issue by artgru** [kee-org/browser-addon#317]
Hi,

Would it be possible to introduce keyboard switching and selecting the right entry with keyboard?
![obraz](https://user-images.githubusercontent.com/37419387/180194736-e3c448cc-fd4e-47e6-a2e5-2c340966f83a.png)

**Comment by luckyrat** [comment]
In Kee 3.11 the popup window will open with the first item in the list selected.

Then up and down arrows navigate the list and enter selects. Escape closes the window and thus falls back to the standard browser authentication dialog. If other interaction occurs to prevent the keyboard focus being on the list itself, Tab will re-focus it.

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
