### ISSUE TITLE
Feature requests: add support for referenced entrys in KeePass2

### ISSUE THREAD

**Issue by Uwe11** [kee-org/browser-addon#318]
KeePass supports duplicating entries and referencing password and username to the original. That leads to having to change a password only for one entry and the duplicate one will be updated automatically. I use this feature quite often when sites are reachable under different addresses.

The content of such a password field starts with"{REF:"

Kee Browser addon is currently not aware of this feature and copies the REF-String in the password/user filed instead of the referenced source.

**Comment by pstiegele** [comment]
It's possible to enable reference support in the Keepass database settings:
https://forum.kee.pm/t/placeholder-handling/1100
