### ISSUE TITLE
Feature Request: Auto unlock for KeePass

### ISSUE THREAD

**Issue by Uwe11** [kee-org/browser-addon#319]
When you configure KeePass to auto lock after a certain time of inactivity (what I would suggest) Kee Browser Addon loses access to KeePass database. So far so good and as expected.

I used to use "KeepassConnector-Edge" as Browser Addon. A very nice feature of this addon is to ask for unlocking the database, when it's locked. So when you open a web page where credentials are asked, "KeepassConnector-Edge" tries to connect to the database and if not reachable it asks for unlocking or even opening the database.

I'd like to see this feature also for Kee Browser Addon.

**Comment by luckyrat** [comment]
I seem to recall that this feature was so annoying to so many people that we had to remove it. Take a look in old issues (maybe the KeeFox repo too) and the community forum if you're interested in digging into the idea a bit more.

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
