### ISSUE TITLE
Toolbar button popup just shows "Loading..."

### ISSUE THREAD

**Issue by luckyrat** [kee-org/browser-addon#32]
From #29 : 

> Not working at all for me on 57.0b1. I get a toolbar icon, and clicking it just shows "Loading...".

Please can anyone experiencing this issue supply some more information about environment, steps to reproduce and browser console log debug output. I've not seen such behaviour myself so can't start looking into the issue without more to go on.

**Comment by aliblong** [comment]
I get this behaviour. Here are some environment details:

Browser:  FF v57.0b6, v57.0b4
Platform: Windows 10
Tools: yarn v1.1.0, web-ext v2.0.0
Build commands:
```
yarn install
gulp watch
web-ext build
```
Console debug output when I reload the addon:
```
Loading failed for the <script> with source “moz-extension://e84e6210-8353-4b14-a1cc-26b34e75f5b8/common/common.js”.  _generated_background_page.html:10
Loading failed for the <script> with source “moz-extension://e84e6210-8353-4b14-a1cc-26b34e75f5b8/background/app.js”.  _generated_background_page.html:12
```
Console debug output when I click on the toolbar icon:
```
Loading failed for the <script> with source “moz-extension://f91c2d88-558b-4ee4-9fa5-012dc2fa0eac/common/common.js”.  popup.html:22
Loading failed for the <script> with source “moz-extension://f91c2d88-558b-4ee4-9fa5-012dc2fa0eac/popup/popup.js”.  popup.html:23
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.  popup.html
```

I also get the following errors in the `about:debugging` page:
```
Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
Reading manifest: Error processing version_name: An unexpected property was found in the WebExtension manifest.
```

**Comment by luckyrat** [comment]
Have you tried it without using web-ext? I've not used that before. Also might be worth trying an alternative build command since I don't typically use "watch" and it's therefore not as well excerised as:

`gulp build; gulp package:beta`

It looks like the main extension code is not being loaded for some reason.

I wouldn't worry about the character encoding or reading manifest errors though.

**Comment by aliblong** [comment]
Looks like I get the same result exactly when I try `gulp build; gulp package:beta`

**Comment by luckyrat** [comment]
There were some build problems with recent upgrades to build dependencies. They were fixed last week so I expect this issue has been resolved. Feel free to re-open with updated build logs and debug console logs if you still see a problem with Beta 4.
