### ISSUE TITLE
[Enhancement] Sometimes the Kee icon overlaps the native one

### ISSUE THREAD

**Issue by ArtyoZ** [kee-org/browser-addon#320]
Hello! Sometimes the Key icon overlaps the native one - which is hiding/displaying the password, for example. Please, fix it or give a possibility to setup the icon's position (left/right) for the entry.

**Comment by luckyrat** [comment]
I think there are already discussions about the possible approaches and drawbacks of a feature like this - check the community forum.

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
