### ISSUE TITLE
Unable to remove Kee entry from Firefox' context menu

### ISSUE THREAD

**Issue by jed84** [kee-org/browser-addon#321]
* Feature requests
* As Kee/Firefox user, I want to be able to remove Kee entry from Firefox' context menu:

![2022-12-01 012729](https://user-images.githubusercontent.com/47121522/204936877-f5448659-8347-44ad-aafc-e545f91e2292.png)

**Comment by luckyrat** [comment]
Please request this on the community forum so it can be tracked and discussed by the rest of the community. I suspect that this will be possible as part of the migration to MV3 in future but it's not something I'm likely to spend much time on myself so may have to be implemented by someone else once that rewrite is completed.

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
