### ISSUE TITLE
Latest Kee (3.9.5) often failed to fill in forms, had to downgrade

### ISSUE THREAD

**Issue by mzso** [kee-org/browser-addon#322]
Hi!
Ever since I upgraded I noticed that some form were not filled, or were missing checkboxes (usually remember login or such), also auto submit didn't work. (Maybe because of this). Anyway. I downgraded to the reliable v2.5.6 (with, old keepass.rpc). And now all of these work fine again.

**Comment by BenjaminBeichler** [comment]
I have the same issues. When I explictitly search for logins the following error is thrown in the developer tools:

``
Error in event handler: TypeError: Cannot read properties of undefined (reading 'sessionFeatures')
    at FormFilling.getRelevanceOfLoginMatchesAgainstAllForms (chrome-extension://mmhlniccooihdimnnjhamobppdhaolme/page/page.js:1:22895)
    at FormFilling.findLoginsResultHandler (chrome-extension://mmhlniccooihdimnnjhamobppdhaolme/page/page.js:1:21898)
    at chrome-extension://mmhlniccooihdimnnjhamobppdhaolme/page/page.js:1:56147
``

Maybe this helps ....

**Comment by luckyrat** [comment]
If you're still experiencing problems with the latest versions of Kee and KeePassRPC, please check out the help available on the community forum.

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
