### ISSUE TITLE
Reference password not working

### ISSUE THREAD

**Issue by Bartek200219** [kee-org/browser-addon#323]
When using with keepass duplicated entry that has references enabled kee doesn't use original username and password but "{REF:...." 

Browser: Edge 109.0.1518.70
Keepass: 2.39.1

Steps to reproduce:
1. Create an entry with username and password 
2. Create a duplicate of 1 entry and set reference in duplication option
3. Change URL in duplicate
4. Go to the new URL

**Comment by thomastoye** [comment]
Same here. (`Ubuntu 20.04.5 LTS` / `Kee 3.10.10` / `KeePass 2.45` / `KeePassRPC 1.14.0.0`)

* Copying a password inside of KeePass works correctly
* Inserting a password using Kee does not work (inserts `{REF:...`)
* Copying a password from the Kee dialog does not work (copies `{REF:...`)

Here is how to create a reference using KeePass:

![image](https://user-images.githubusercontent.com/3396772/220309236-5641b4a2-7f8c-48d2-98f2-9d529608574e.png)

**Comment by luckyrat** [comment]
https://forum.kee.pm/t/placeholder-handling/1100

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
