### ISSUE TITLE
how can i enable the option in chrome "offer to save passwords" without disabling the extension?

### ISSUE THREAD

**Issue by UriZafrir** [kee-org/browser-addon#328]
hello
I am using kee browser extension.
how can i enable the option in chrome "offer to save passwords" without disabling the extension?
I would like chrome to offer to save passwords and also use the extension.

I suspect it has something to do with this function in main.ts but I don't know what to change:
```javascript
function saveOfferToSavePasswords(e) {
    e.preventDefault();

    if (siteModeAll) {
        const save = (
            document.getElementById("pref_notifyBarRequestPasswordSave_label") as HTMLInputElement
        ).checked;
        configManager.current.siteConfig.pageRegex["^.*$"].config.preventSaveNotification = !save;
    } else {
        const value = (document.getElementById("requestPasswordSaveSelect") as HTMLSelectElement)
            .value;
        const preventSave = value === "Inherit" ? null : value == "No" ? true : false;
        const siteConfigLookup = configManager.siteConfigLookupFor(
            specificSite.target,
            specificSite.method
        );
        siteConfigLookup[specificSite.value].config.preventSaveNotification = preventSave;
        siteConfigLookup[specificSite.value].source = "User";
    }
    configManager.save();
}
```

Thanks in advance

**Comment by vanowm** [comment]
The only current solution is to disable the addon...
This has been a long-time plaque #55

**Comment by luckyrat** [comment]
Yeah, latest on the topic is https://forum.kee.pm/t/kee-has-disabled-the-browsers-inbuilt-ability-to-save-passwords/3968/4

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
