### ISSUE TITLE
Feature Request: Form/Input discovery based on CSS selectors

### ISSUE THREAD

**Issue by profet23** [kee-org/browser-addon#329]
There are numerous websites that choose to not have static "Name" or "Id" fields or they simply omit these attributes altogether. 

One example is:

https://www.linkedin.com/mynetwork/  (the search at the top of the page)

It would be nice to be able to omit/include forms utilizing CSS selectors and not only form/input names and a id's.

**Comment by luckyrat** [comment]
These sorts of discussions are best had on the community forum but in brief, it's an idea I've wanted to explore for many years but the precise way the feature could work does need more planning and it's possible that other changes to the way we identify and work with form fields could negate the need for the feature altogether.

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just updated to the latest GitHub issue template system to try to make that clearer before one takes the time to write up an issue here).
