### ISSUE TITLE
Firefox freezes after entering SRP authorisation code

### ISSUE THREAD

**Issue by akyag** [kee-org/browser-addon#33]
I have tried kee versions from alpha 5 and nothing has worked yet. With alpha 8, it keeps asking me for authorization and once I enter the code, it instantly locks up my Firefox. I have no option but to force quit FF. At the next start, same thing happens again, starting with authorization window popping up again.
I am on fedora 26, Firefox 58.0a1 (2017-10-01) (64-bit)

**Comment by luckyrat** [comment]
Possible duplicate of #27 ?

**Comment by akyag** [comment]
Let me do some more testing. I will create a new profile and start with just kee...

**Comment by luckyrat** [comment]
Pretty sure this was a duplicate of #27 and can therefore be closed. Let me know if the problem still occurs.
