### ISSUE TITLE
Firefox sometimes isn't loading pages anymore

### ISSUE THREAD

**Issue by cypressious** [kee-org/browser-addon#38]
In #27 two different issues were discussed. This issue is about Firefox simetimes not loading pages anymore.

The UI is still responsive and there is no high CPU usage, but web pages just aren't loaded anymore. Opening the dev tools shows that no requests aren't even made.

After restarting Firefox everything is back to normal.

I'm on Windows 10 64 bit. For me, this bug regularely happens right after booting up the PC and starting FF for the first time. After a couple of minutes, pages stop loading. After restarting FF, it usually works until I reboot the PC.

**Comment by KingPrawn22** [comment]
Same thing happening for me. Works fine for about half hour, then suddenly it's if my internet connection has cut out. Firefox remains responsive but just doesn't load pages until I either restart it, or disable this add-on. Have a a good few other add-ons, so tried disabling them all and re-enabling them one by one but the issue still occurred independent of what else was enabled.

Not a huge issue for me, just using Keepass directly until the official release of 2.0.

**Comment by kuon** [comment]
I noticed the same issue, but sometimes, after like 5 minutes, firefox suddenly "unlock" and load all pages at once.

**Comment by luckyrat** [comment]
As discussed in #27, this is a different symptom of the same problem. Closing as a duplicate.
