### ISSUE TITLE
Finding no submit button prevents autofill

### ISSUE THREAD

**Issue by hexd0t** [kee-org/browser-addon#42]
IMO, even if no suitable submit button is found, but Username and Password Fields are, the Autofill should succeed instead of aborting the whole matching process ("No submission possibility found in this form")

**Comment by luckyrat** [comment]
Quite possibly yeah. If there aren't any negative side-effects from this, the approach could be to check for the existence of content in `matchResult.submitTargets[]` as part of the decision whether to submit the form.

**Comment by nithinphilips** [comment]
Having the same problem. I have site that uses a regular `<a>` link and onClick javascript (`form.submit()`) to submit the form. Kee won't fill in the credential on this site.
