### ISSUE TITLE
Support <input type="button" />

### ISSUE THREAD

**Issue by hexd0t** [kee-org/browser-addon#43]
Currently, only input type submit or image are found without an additional role attribute. Type=button should be regarded as a possible submission possibility as well.

**Comment by luckyrat** [comment]
I agree.

Should probably be given a match score between current priority 3 and 4? Or maybe equal to p3? I'm leaning towards the former but evidence of real world usage data could easily convince me otherwise.

        // Priority 1: button within form provided: @type != reset
        // Priority 1: button outside form with @form attribute provided: @type != reset
        // Priority 2: input @type=submit within form
        // Priority 3: input @type=image within form
        // Priority 4: <any element>@role=button within form provided: there is only 1 match
        // Priority 5: <any element>@role=button outside form provided: there is only 1 match

Should be a relatively simple change to the code in formFilling.ts:

`private findSubmitButton (form: HTMLFormElement, submitTargetNeighbour: HTMLElement) ...`

**Comment by hexd0t** [comment]
Not exactly sure if I correctly grasped the scoring system, its a bit Magic Number heavy.
```
// Priority 1: button within form provided: @type != reset
// Priority 1: button outside form with @form attribute provided: @type != reset
// Priority 2: input @type=submit within form
// Priority 3: input @type=image within form
// Priority 4: <any element>@role=button within form provided: there is only 1 match
// Priority 5: <any element>@role=button outside form provided: there is only 1 match
// Priority 4: input @type=button within form
// Priority 5: <any element>@role=button within form provided: there is only 1 match
// Priority 6: <any element>@role=button outside form provided: there is only 1 match
```

```
Prio | Base score
(new)| was | new 
-----+-----+-----
  1  |  6  |  6
  2  |  4  |  5
  3  |  3  |  4
  4  | N/A |  3
  5  |  2  |  2
  6  |  1  |  1
```

I did not change the good-word/bad-word modifiers and reused the same detection as is applied to the input submits.
