### ISSUE TITLE
MS Edge version

### ISSUE THREAD

**Issue by pcause** [kee-org/browser-addon#45]
Now that there is a web extension version can you create an edge version?  I use firefox but have business need to use edge on many occasions and hate not having keefox

**Comment by luckyrat** [comment]
I'm focussing on getting as good an experience for Firefox users first, then Chrome should be able to follow very soon.

Edge is more uncertain - Microsoft don't seem to be taking extensibility all that seriously and I have frequently come across documents and comments that indicate they have yet to implement WebExtensions accurately enough to make it an easy job to get it working. I've not had time to put a concerted effort into validating and working around these issues though, merely noted that there are some and that I should therefore delay work on an Edge version until the two main browsers are running smoothly.

I'm more than happy to accept contributions to enable Edge support, as long as the changes don't compromise the Firefox or Chrome experience for users.

**Comment by t0lik** [comment]
I tried the extension in MS Edge and found that Edge does not support commands.Command:
[commands](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#commands)

Error:
SCRIPT5007: SCRIPT5007: Unable to get property 'onCommand' of undefined or null reference
app.js (41,9)

(commands.ts line 5)

**Comment by jpickerell** [comment]
Appreciate your work on an extension version of KeeFox for Firefox and Chrome. Would love to see an Edge extension as well!

**Comment by luckyrat** [comment]
Closing this broad issue in favour of a new project which we can add specific issues to as and when we need: https://github.com/kee-org/browser-addon/projects/3

**Comment by OLLI-S** [comment]
I would also like to see an extension for Microsoft Edge (my primary web browser at home).
At work we switch to Windows 10 now and so Edge will be also there the default browser (before it was Firefox).
So at home ad at work I need an extension for Microsoft Edge.
Then I will start using Kee ans also donate.
