### ISSUE TITLE
All web requests lock up after some time

### ISSUE THREAD

**Issue by hexd0t** [kee-org/browser-addon#46]
When activating the Kee addon, everything works as expected for some random amount of time.
Suddenly, while doing a web-based request (page load, resource load, xhr, ... via http or https), one of nightly's child processes goes to 25% CPU (single core max load) and no requests are resolved anymore.
Chrome pages (eg about:settings) still work. When opening the Network tab in the dev console, the requests don't even show up.
![kee_1](https://user-images.githubusercontent.com/775150/31994595-82f2546c-b981-11e7-818b-4f3a1668ce09.png)

As soon as I kill the subprocess, all the requests do resolve, but now none of my addons work anymore.
Next to Kee this profile contains uBlock Origin and uMatrix, both on their beta channels, but the problem even occurs when disabling them. I have not met the problem while keeping Kee disabled.

I'm currently using Kee Alpha 15 in Nightly x64 on Windows 7.
Nightly is at `rev/a80d568a417ea8410cd2d874c1e0267fb92888fe`, yesterday's nighly build
This happened for some time now though, I just didn't make out Kee to be the cause until now.
I'm using a PAC-File to determine Proxies (which are HTTP based).
The browser log is appended by an entry `Error: WebExtension context not found!` in ExtensionParent.jsm;829;13, but this also appears sometimes when the lockup doesn't happen, so it might be unrelated.

The problem seems to occur faster if more requests are made, for example listening to Spotify's Web client, which only downloads small chunks of audio per request, ususally triggers the problem within 1h tops.

**Comment by SinafdeGiraf** [comment]
Might fit in with issue https://github.com/kee-org/browser-addon/issues/27 (?)

**Comment by hexd0t** [comment]
Yes, seems that way. Not sure how I missed that when scanning for similar issues...
