### ISSUE TITLE
Login entry navigation with arrow keys

### ISSUE THREAD

**Issue by NCC1701M** [kee-org/browser-addon#48]
When I use the shortcut ctrl+shift+2 to insert the login data and there are several possible login data entries I can't use the arrow keys to navigagte between those entries. I had to use the Mouse instead. This is a little annoying because it would be faster with the arrow keys.

**Comment by luckyrat** [comment]
Kee 2.2 will enable up/down navigation within the:
* matched logins list
* list of search results
* list of password profiles for new password generation
