### ISSUE TITLE
Feature Request:  Time-Based One-Time Password Support

### ISSUE THREAD

**Issue by richard-scott** [kee-org/browser-addon#49]
It would make this perfect if you could support the submition of [TOTP ](https://keepass.info/plugins.html#keeotp) passwords if one is enabled for the entry being used.

**Comment by luckyrat** [comment]
Thanks for the suggestion. Please can we move discussion of this to the [community forum](https://forum.kee.pm/t/kee-and-otp-codes/1037) until we identify a definitive way forward.

**Comment by iyesin** [comment]
Why move discussion to separate forum? Is this area bad for development discussion?
