### ISSUE TITLE
keepass's other versions?

### ISSUE THREAD

**Issue by rezad1393** [kee-org/browser-addon#5]
can the new addon be written with other ports of keepass in mind?
like keepassxc?
right now in linux the addon uses wine and mono just to run keepassx and it has no other use for that specific program(keepass original) other than keepassRPC. the wine verison it not integrated nicely in linux.
please make it so that the addon will not depend on the application it communicates with but only on existence of keepassRPC.  
thank you.

**Comment by luckyrat** [comment]
The add-on does depend only on the existence of KeePassRPC. Currently, KeePassRPC is only available in KeePass 2 but there's no reason someone couldn't port it to other KeePass ports. That's not something I'll have time to do personally and is out of scope for this project but I'll offer advice to porters where possible.

**Comment by rezad1393** [comment]
then the part in option of addon that ask for keepassx2 installation path and mono path is optional?
