### ISSUE TITLE
keefox 2.0.0 alpha17 : .htpassword do not work 

### ISSUE THREAD

**Issue by Marcosdw** [kee-org/browser-addon#50]
Hello,

The login and password of .htpassword accesses do not work. The authentication window is empty and can not be filled by keefox because of a hang.

Please fix the bug

Thank you

Greetings
_______________________________________________
Sorry I use an online translator French / English

**Comment by luckyrat** [comment]
That was an intentional experiment (an option would allow you to re-enable). I've now disabled the experiment so it will go back to normal for alpha 18: https://github.com/kee-org/browser-addon/releases/tag/2.0.0-a18
