### ISSUE TITLE
Basic Auth support requires open DB before page load

### ISSUE THREAD

**Issue by cypressious** [kee-org/browser-addon#58]
I think Basic Auth was supported in an earlier version of the Web Extensions version but now it's gone. Any reason why?

**Comment by luckyrat** [comment]
It's working for me. Can you provide an example URL where it doesn't work and more detail about the behaviour you see?

**Comment by cypressious** [comment]
Ah, the db needs to be open and unlocked for it to work. It doesn't work when the credentials dialog is already open and you open the db after the fact. I guess that's fixable?

**Comment by luckyrat** [comment]
> I guess that's fixable?

Unfortunately I don't think so. The WebExtensions API is such that once the standard browser credentials dialog is shown, no extension can interfere later.

The only thing we might be able to do is auto-refresh the page but that feels pretty heavy handed and would need more prolonged beta testing than we have time for at the moment.

**Comment by cypressious** [comment]
I actually meant to write "unfixable", sorry. This can probably be closed.

Kirill Rakhman

Am 09.11.2017 22:59 schrieb "Chris Tomlinson" <notifications@github.com>:

**Comment by luckyrat** [comment]
Yeah, I've updated the title to aid discoverability in future but agree we should close.

**Comment by cypressious** [comment]
@luckyrat I found a bug with Basic Auth. When a db is unlocked but you don't have the matching entry and you close the KeeFox dialog, the basic auth dialog doesn't appear. There's basicly no way to enter the credentials manually, when a db is unlocked.
