### ISSUE TITLE
kee 2.0.0.21b3 not autofilling VMware login page

### ISSUE THREAD

**Issue by athanasio** [kee-org/browser-addon#60]
kee 2.0 is not able to fill the login form in VMware web client pages - it doesn't find any matching logins. Previous versions (1.7.x) were able to find them, and other similar tools do as well (eg keepass-httpconnector) in both Firefox 56.0.2 and 57rc1.
I've tested against a number of different VMware installations as well, and they all have the same problem.

**Comment by luckyrat** [comment]
Please can you test with Beta 5? https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/2.0.0.23b5

If that still doesn't work then I'll need an example page to look at, ideally with a working demo login but I know that's often not possible.

**Comment by athanasio** [comment]
Hello, latest beta seems to have resolved this. I'll keep an eye if the problem continues in other places.
