### ISSUE TITLE
Basic Auth dialog should make it possible to distinguish between DBs

### ISSUE THREAD

**Issue by cypressious** [kee-org/browser-addon#63]
I have two DBs that have the same entries but with different passwords. In the Basic Auth window, I can't tell which entry is from which db.

**Comment by luckyrat** [comment]
The database name is displayed in the tooltip when you hover on the item. I don't think we have enough space to include it in the popup dialog.

**Comment by luckyrat** [comment]
Unless we do a redesign of the Basic Auth window for some other reason, I'm not intending to make this change so will close at least for now.
