### ISSUE TITLE
[Feture] Donate

### ISSUE THREAD

**Issue by nailyk-fr** [kee-org/browser-addon#64]
Many thanks for all your work. 
As usual, we only noticed something is essential while it is not working. So I just figured out I cannot live without keefox. 
After reading a bit your profile &| keefox.org I was not able to find a _donate_ button. 
Can you please add one, Id really like to support your efforts with some beers, and think some other people will be glad to offer you something too :)

Many thanks for your involvement.

**Comment by develguebil** [comment]
I agree 100% 👍 Thank you for all your work and commitment

**Comment by dmsims** [comment]
+1

**Comment by luckyrat** [comment]
Thanks for asking everyone.

The donate page is at https://www.paypal.me/luckyrat

It was previously only linked from a relatively obscure part of the Mozilla add-ons website. I've now added it to the header of the https://www.kee.pm website and will look out for other places I can add it when I get a chance.

Incidentally, the new Firefox add-ons website does make the link a little bit more prominent too - I'm not sure when the new site rolls out to everyone but sometime in the next 24 hours would be a good bet.

**Comment by nailyk-fr** [comment]
Thanks!
