### ISSUE TITLE
Closing network auth dialog does not trigger standard http auth dialog in Firefox

### ISSUE THREAD

**Issue by unixfox** [kee-org/browser-addon#65]
Currently I can't fill manually a http auth dialog because Kee wants to fill the dialog in my place and if I close the Kee box that ask me to choose a credential the page loads indefinitely.
![image-20171110-01](https://user-images.githubusercontent.com/4016501/32678836-5a991bdc-c664-11e7-9c3c-817d2519b885.png)

So is it possible to disable this behavior or let the http auth dialog appears after closing the Kee box?

**Comment by luckyrat** [comment]
This is a bug. The standard dialog appears in Chrome and I think it used to in Firefox but either way, I can easily fix it this weekend.
