### ISSUE TITLE
Network Authentication popup blank/empty/white

### ISSUE THREAD

**Issue by luckyrat** [kee-org/browser-addon#71]
Sometimes the Network Auth window will appear to contain no content.

This is due to a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1400252) which we'll keep an eye on in case newer versions of Firefox introduce a way to workaround the bug.

![capture du 2017-11-13 12-21-54](https://user-images.githubusercontent.com/1211375/32724067-b84ee07c-c867-11e7-8c0b-a3550acbe795.png)

You should be able to reveal the contents by resizing the window. For example, you could drag the borders of the window or minimise and then maximise it.

A similar problem previously affected the SRP authorisation window until that was moved to a tab (#39)

**Comment by Marcosdw** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1400252#c6

**Comment by Marcosdw** [comment]
@luckyrat , see : https://bugzilla.mozilla.org/show_bug.cgi?id=1400252#c9 redirect bug on : https://bugzilla.mozilla.org/show_bug.cgi?id=1408446

**Comment by bepixeld** [comment]
I have same problem under Linux/Ubuntu with Firefox 57. OK the blank window seems a firefox bug.
In addition if I have no credentials in KeePass, in the popup is written, that I should close the popup for manual input. But if I close it, there is no other popup visible for manual input. The website is then still waiting for input.
Only if I disable Kee-plugin I am able to manual input my credentials.
Thank you for help.

**Comment by dg500** [comment]
Another workaround under Ubuntu with FF 57 is a right mouse click in the empty window.

**Comment by Perlover** [comment]
+1
Same bug, always
And yes, workaround as right click in empty window

**Comment by MegaV0lt** [comment]
I have the same issue. White window with FF57 on Linux Mint Cinnamon 64 Bit

Also temporary working is to resize the window with the mouse

**Comment by luckyrat** [comment]
I've developed a workaround for this issue which will be included in Kee 2.2.

I also found and reported bug #149 while looking into this. It likely affects the same people that were affected by this issue.

**Comment by luckyrat** [comment]
I'll leave this issue open since we'll want to make occasional checks on the status of the blocking Firefox bug and remove the workaround when that is fixed in all supported versions of Firefox. Other than that, there's nothing left to do on this issue so it's become an admin task rather than a bug fix and I'll update the labels accordingly.

**Comment by luckyrat** [comment]
Seems to be fixed according to Bugzilla so we can remove the workaround after the next ESR is established (end of 2019) and just double check it's resolved for us too.

**Comment by luckyrat** [comment]
Since the underlying cause of this was running extensions in the main Firefox process and this has not been the case since at least Firefox 68 ESR, I will remove the workaround code for Kee version 3.3 and higher. Please let me know during the beta testing period of 3.3 if the issue re-occurs on your system configuration.
