### ISSUE TITLE
Display database filename if it has no name

### ISSUE THREAD

**Issue by dertuxmalwieder** [kee-org/browser-addon#72]
I use the latest Quantum version (currently version 57 at 64-bit) with KeePass 2.37.

While Kee is working nicely in its recent versions (and even the pop-up finally looks good in Kee beta 5), there is one thing that bothers me: It just can't read my database name. I mean, it does not *really* matter since I only use one database, but it looks like some string is just *not filled* in the pop-up.

To me, it looks like the string `loggedIn_tip` does not fill the `$1` variable if the database is default. In this case, it should probably get a better wording...?

**Comment by luckyrat** [comment]
What do you meant by "database is default"?

I have only one database open and it correctly shows the database name.

Are you sure your database has a name?

**Comment by dertuxmalwieder** [comment]
Ah, I thought it would just use the file name. No, I have not set the database name - but I assume that this is not a special case, most people probably won't define a database name if they just have one database...

Either way, Kee should probably detect missing database names and not display "you use the '' database". :-)

**Comment by luckyrat** [comment]
Yeah, we'll need a new string (and one for the multiple database situation). Probably "You are logged into your unnamed database" is a good starting point.

**Comment by auanasgheps** [comment]
Hey guys, I'm testing the app because I'm the Italian translator, and I've noticed the same issue. Initially I thought I missed the lookup value, but in reality I didn't specify any name to the DB, I din't even know about that feature.
I would suggest that if there is no name, Kee would return the filename of the open DB.
I don't know if there are technical limitations in doing so.

**Comment by Asimov500** [comment]
I just noticed this. So now I have gone into database settings and named my databases. However I notice it only shows the name of the database you currently have active eg the one you have clicked the tab on.

**Comment by luckyrat** [comment]
> However I notice it only shows the name of the database you currently have active eg the one you have clicked the tab on.

That's how I intended it to work. It sounds like you had a different expectation?

**Comment by Asimov500** [comment]
I just thought it would list the databases you have loaded. I very often have up to 2 or 3 databases loaded at the same time. eg work, home and projects. It is not a great problem as long as it fills in the passwords for all of course.

**Comment by tblasche** [comment]
I just opened PR #133 which displays the password database file name when no name is set for the opened password database explicitly.

**Comment by luckyrat** [comment]
Thanks to @tblasche this will be included in the next beta release.
