### ISSUE TITLE
Error on Chrome with some sites

### ISSUE THREAD

**Issue by EddieGreen** [kee-org/browser-addon#73]
![2017-11-13_10-02-17](https://user-images.githubusercontent.com/5681968/32720007-28aad1ea-c85a-11e7-816a-e1782a31eef8.jpg)

This bug occurs at the point that the entry is selected in the Kee dropdown. The result is that the page is reloaded and the entries cleared. Does not happen on all sites tested. Kee set to fill in form not submit. running beta 5

**Comment by luckyrat** [comment]
@EddieGreen : Can you supply a URL for any site that is affected?

Anyone see similar behaviour in Firefox yet?

**Comment by EddieGreen** [comment]
The site I'm trying to log into is private, but this is the app:

http://demo.mailenable.com User: MEDEMO@Demonstration and pw:demo

There are several sites I've tested for which Kee does not offer to save passwords, this is one of them.

I can log in manually. I can create an entry in KeePass manually and Kee will work as expected when visiting the site.

I believe that there must be some problem with retrieving previously stored entries automatically created by KeeFox in earlier versions. 

I'd like to install Kee on FF but I'm not getting an authorisation page from Kee when any version above 1.7 is loaded. Will post new issue about this separately.

**Comment by luckyrat** [comment]
I would expect this site to never work with password managers. It has an entirely custom javascript login method. The form fields are just superficial but it doesn't work like other forms on the internet.

I don't see the exception message in Firefox and still see the behaviour of the page reloading upon submission (this is because Kee does not know which magic bit of javascript to run on the page in order to send the correct magic data to their login server). Most web sites with similar magic can still work because they use standard web technologies to build their forms - unfortunately this site doesn't do that.

I'll take another look in Chrome for the exception message soon but will have to remain focussed on Firefox issues today.

**Comment by EddieGreen** [comment]
The demo site has a script to login automatically because it's a demo. Log out then log back in with credentials supplied, that script doesn't run again

**Comment by EddieGreen** [comment]
Okay... got FF 57 working with latest Kee.

Issue reproduced. Existing entry causes error. new entry does not.

**Comment by EddieGreen** [comment]
This is what is being logged:

`In browser content page script, received message from background script
Logger.ts:81:36
Logging system initialised at Mon Nov 13 2017 12:51:50 GMT+0000 (GMT Standard Time)
Logger.ts:93:36
iframe page starting
Logger.ts:81:36
Logging system config updated at Mon Nov 13 2017 12:51:50 GMT+0000 (GMT Standard Time)
Logger.ts:93:36
iframe page ready
Logger.ts:93:36
In iframe script, received message from background script: 
Logger.ts:81:36
setting 28 matched logins
Logger.ts:81:36
In browser content page script, received message from background script
common.js:175:17
fillAndSubmit started. automated: false, formIndex: null, loginIndex: 27
common.js:175:17
We are allowed to auto-fill this form.
common.js:175:17
Going to auto-fill a form
common.js:175:17
_fillManyFormFields started
common.js:175:17
We've received the data we need
common.js:175:17
Filling form fields for page -1
common.js:184:17
Auto-overwriting fields
common.js:184:17
Suitablility of putting data field 0 into form field 0 (id: txtPassword) is 116
common.js:175:17
We will populate field 0 (id:txtPassword)
common.js:184:17
_fillManyFormFields started
common.js:175:17
We've received the data we need
common.js:175:17
Filling form fields for page -1
common.js:184:17
Auto-overwriting fields
common.js:184:17
Suitablility of putting data field 0 into form field 0 (id: txtUsername) is 116
common.js:175:17
Suitablility of putting data field 1 into form field 0 (id: txtUsername) is 0
common.js:175:17
Suitablility of putting data field 2 into form field 0 (id: txtUsername) is 0
common.js:175:17
Suitablility of putting data field 3 into form field 0 (id: txtUsername) is 0
common.js:175:17
Suitablility of putting data field 0 into form field 1 (id: ddlLanguages) is 0
common.js:175:17
Suitablility of putting data field 1 into form field 1 (id: ddlLanguages) is 116
common.js:175:17
Suitablility of putting data field 2 into form field 1 (id: ddlLanguages) is 26
common.js:175:17
Suitablility of putting data field 3 into form field 1 (id: ddlLanguages) is 0
common.js:175:17
Suitablility of putting data field 0 into form field 2 (id: ddlSkins) is 0
common.js:175:17
Suitablility of putting data field 1 into form field 2 (id: ddlSkins) is 26
common.js:175:17
Suitablility of putting data field 2 into form field 2 (id: ddlSkins) is 116
common.js:175:17
Suitablility of putting data field 3 into form field 2 (id: ddlSkins) is 0
common.js:175:17
Suitablility of putting data field 0 into form field 3 (id: chkRemember) is 0
common.js:175:17
Suitablility of putting data field 1 into form field 3 (id: chkRemember) is 0
common.js:175:17
Suitablility of putting data field 2 into form field 3 (id: chkRemember) is 0
common.js:175:17
Suitablility of putting data field 3 into form field 3 (id: chkRemember) is 116
common.js:175:17
We will populate field 0 (id:txtUsername)
common.js:184:17
We will populate field 1 (id:ddlLanguages)
common.js:184:17
We will populate field 2 (id:ddlSkins)
common.js:184:17
We will populate field 3 (id:chkRemember)
common.js:184:17
Syncing UUID to: 86F42627A99A1042A65724C1DAB9A5EA
common.js:175:17
Matched login request is not being auto-submitted.
common.js:175:17
In browser content page script, received message from background script
common.js:175:17
Navigated to https://mail.eddiegreen.com/Mondo/lang/sys/Login.aspx
**Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.
LIBMerge_10.00.js:16:31951**
Logging system initialised at Mon Nov 13 2017 12:51:57 GMT+0000 (GMT Standard Time)
common.js:184:17
content page starting
common.js:175:17
content page ready
common.js:184:17
In browser content page script, received message from background script
common.js:175:17
Logging system config updated at Mon Nov 13 2017 12:51:57 GMT+0000 (GMT Standard Time)
common.js:184:17
scanForOrphanedFields took: 0
common.js:175:17
Finding matches in a document. readyState: complete
common.js:184:17
findMatches processing 1 forms
common.js:175:17
about to get form fields
common.js:175:17
`

**Comment by EddieGreen** [comment]
Error in line:
`Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.
LIBMerge_10.00.js:16:31951
`

**Comment by EddieGreen** [comment]
Confirming fault is in site library rather than Kee. How come this fault is not generated when form filled with new manually created entry

**Comment by vanackere** [comment]
I believe this is a duplicate of https://github.com/kee-org/browser-addon/issues/105 and may be closed

**Comment by luckyrat** [comment]
I think there might have been two different errors in this report (the original screenshot - duplicate of #105 - and the text log). Are you still seeing either problem with Kee 1.3 @EddieGreen ? If not, I'll close this after a few weeks.

**Comment by EddieGreen** [comment]
I've not had further issues. Thanks for looking into it.
