### ISSUE TITLE
Useless notifications

### ISSUE THREAD

**Issue by gauthier-delacroix** [kee-org/browser-addon#74]
Hi,

Just installed 2.0b5, which works just fine on Vivaldi, but I get notifications "Do you want Kee to save this password?"...even when I just logged though Kee.

It may be cause by the fact that I only use KeepassRPC specific URL regexp patterns instead of the native KeePass URL field.

**Comment by luckyrat** [comment]
I think it's just down to the fact that Kee does not know you've logged in using credentials it supplied.

If you use the matched logins panel to select and submit the same details, the notification does not appear.

I don't really want to have to inspect the contents of the KeePass database upon every form submission (like KeeFox used to do) so will have a think about other potential solutions to this.

**Comment by gauthier-delacroix** [comment]
Maybe you could juste disable the notification if at least one credential is found (even if it's not used for login).

**Comment by luckyrat** [comment]
This is fixed in beta 6: https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/2.0.0.24b6
