### ISSUE TITLE
PDF input field auto fillable by Kee

### ISSUE THREAD

**Issue by adaur** [kee-org/browser-addon#77]
The addon seems to treat fields in the PDF reader as potential login/password fields

![pdf](https://user-images.githubusercontent.com/959078/32749249-c71b97a6-c88c-11e7-9529-8105390bbf96.png)

**Required fix**:

Add "pageNumber" to the list of blacklisted form field IDs in the default top-level site-specific config. As well as the change to the list of strings in the source code, there will also need to be a new data migration created which safely appends this new value to the end of each user's existing configuration when the updated version is first installed.

**Comment by luckyrat** [comment]
Fun. I'm a little surprised that Firefox injects add-on content scripts into the built-in PDF reader. That may be a bug worth raising with them - at the very least there probably should be some documentation about it.

Have you seen any example of a PDF with embedded form fields? It would be interesting to see if those get filled in too or just the chrome at the top of the PDF viewer.

**Comment by adaur** [comment]
It's weird: I don't have the issue mentionned here with this fillable PDF http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf while I do when the PDF is not fillable

**Comment by luckyrat** [comment]
I see the issue on that fillable PDF @adaur - maybe something else caused you to not see it.

This is very related to https://forum.kee.pm/t/how-to-configure-the-new-contextual-kee-buttons/278 but I'll keep this issue open here since I think we might want to address this specific case before working on a wider solution.

I think we should simply avoid inserting the context button into fields of type "number" like this one.

**Comment by charlesroper** [comment]
I blacklisted #pageNumber as a quick fix. Blacklisting all `type="number"` fields seems like a reasonable overall solution on the surface, but I suspect there may be some sites that use a number for username and/or password (a PIN, for example).

**Comment by luckyrat** [comment]
Yeah I think you're right @charlesroper . There're probably not a huge number of passwords like that but there might be a few so I think the fix here should be to add "pageNumber" to the list of blacklisted form field IDs in the default top-level site-specific config.

As well as the change to the list of strings in the source code, there will also need to be a new data migration created which safely appends this new value to the end of each user's existing configuration when the updated version is first installed. That's not too hard, but possibly beyond my vague idea of what constitutes a good first issue so I'll remove that label now and edit the original post with the updated plan.

It is still feasible that some login forms will use pageNumber as an ID for a field in their login form but no more so than some of the other highly unlikely terms we already blacklist by default and I think the risk is lower than a blacklist of the number input type. A quick look through the publicwww.com source code search doesn't bring up any concerning uses of #pageNumber in the top 100K sites so I think that's good enough to say we can go ahead with this change.

**Comment by luckyrat** [comment]
I think that this was an upstream bug in Firefox which they have since resolved. Is anyone still seeing the issue in Firefox 63+ ?

If not, I'll close this issue.
