### ISSUE TITLE
Kee 2.0.024b6 not working with BitBucket login

### ISSUE THREAD

**Issue by dcardin** [kee-org/browser-addon#79]
Hi! I think when all the wrinkles are gone, it will be great!
Here's an example site that used to work and now the form login is not detected.
https://bitbucket.org/account/signin/

I even updated the preferences to add aid-login-form to whitelist the form id, but it still doesn't work.
Thanks!

**Comment by dcardin** [comment]
Still present in 2.0.025

**Comment by luckyrat** [comment]
Please follow this discussion on the support forum: https://forum.kee.pm/t/kee-not-working-on-bitbucket-and-firefox/877
