### ISSUE TITLE
Latest Kee 2.0.0.25 fails to fill credentials with Firefox 57 on specific site

### ISSUE THREAD

**Issue by juxeii** [kee-org/browser-addon#80]
Hi,

I have credentials for this website: https://www.dwservice.net/
Everything was working fine until today Firefox 57 came out.
Now when opening the above website, Kee does not fill anything.
Kee will fill the credentials only when you open a different tab and switch back to the site.
Can someone confirm this?

Thx,
Juergen

**Comment by elgonzo** [comment]
Can confirm for the login form of https://bugs.kde.org/

**Comment by elgonzo** [comment]
Can confirm for https://bugs.kde.org.
Same behavior, same workaround as described by juxeii above.

**Comment by luckyrat** [comment]
FFTusername is purely an indication that Kee sees it as the "primary" (first) text field, where "text field" is loosely defined as any field with text entry except passwords or numerical fields. That won't have a direct impact on whether the site login form can be filled in or not. I'll try to take a look at the specific sites at the weekend in case there is something that can be done to improve compatibility.

Did the sites work in KeeFox 1.7?

**Comment by elgonzo** [comment]
> Did the sites work in KeeFox 1.7?

Don't know whether it worked in the old KeeFox. I just created bugs.kde.org account (with the current Kee then creating the KeePass entry with the credentials). That was when noticed the problem with Kee and bugs.kde.org, which led me to finding the bug report here and responding to it.

I did a quick check with my existing github, Toms Hardware and StackOverflow accounts. The KeePass entries for all those were created with the old XUL-based KeeFox quite some time ago. Kee has no problems with logging me into these three sites.

**Comment by elgonzo** [comment]
I found another site that exhibits the same problem (and is solvable with the "switch to another tab and back" workaround): https://www.nexusmods.com

And I know for sure that this site worked with the old XUL-based KeeFox.

**Comment by juxeii** [comment]
@luckyrat Yes, https://www.dwservice.net/ did work with KeeFox 1.7.

**Comment by elgonzo** [comment]
For me, Kee fills the log-on fields when switching back from another tab (and also submits the forms as mandated by my Kee settings). Like you, i also have only one entry for the problematic sites i have encountered. Can't speak for juxeii though, obviously.

**Comment by juxeii** [comment]
Same is true for me -> only one entry for the site.

**Comment by juxeii** [comment]
Sorry to bring this up again. Are there any updates on the issue?

**Comment by luckyrat** [comment]
Please search the community forum for similar problems / websites and create a new discussion there if still applicable with Kee 2.3 - it's easier to discuss related issues and steps to reproduce on there. We can then create specific issues on GitHub for fixing problems with Kee if we find something actionable or keep information about workarounds, etc. in the same place.

https://forum.kee.pm

Thanks.
