### ISSUE TITLE
Login to Total Commander forum not working anymore

### ISSUE THREAD

**Issue by elgonzo** [kee-org/browser-addon#81]
Kee fails to fill the login form for the Total commander forum at both URLs https://ghisler.ch/board and https://ghisler.ch/board/login.php.
It seems i can't find a way to convince Kee to fill the form. The workaround described in issue #80 does not work here.

When opening the login page for the TC forum, the browser console shows the following:
```
GET https://ghisler.ch/board/login.php [HTTP/2.0 200 OK 153ms]
received message from web socket  common.js:171:17
starting webcrypto decryption  common.js:171:17
decryption stage 'data prep 1' took: 0  common.js:171:17
decryption stage 'key hash' took: 1  common.js:171:17
decryption stage 'data prep 2' took: 0  common.js:171:17
decryption stage 'generate HMAC' took: 1  common.js:171:17
decryption stage 'import key' took: 0  common.js:171:17
decryption stage 'aes-cbc' took: 1  common.js:171:17
decryption stage 'utf-8 conversion' took: 1  common.js:171:17
In browser content page script, received message from background script  common.js:171:17
fillAndSubmit started. automated: true, formIndex: undefined, loginIndex: undefined  common.js:171:17
Relevance of form is 0 common.js:171:17
The most relevant form is #0  common.js:171:17
We are allowed to auto-fill this form.  common.js:171:17
No logins for form.
```
This looks to me like Kee found the login form on the web page but failed to obtain a matching entry from KeePass. Although, KeePass has a matching entry with correct URL information and entry behaviors set to "Use KeeFox settings" (which are auto-fill and auto-submit).

**Comment by elgonzo** [comment]
I discovered some behavior that solved the issue for me and that might help finding fixing this issue.

In my KeePass entry, the URL was set to https://ghisler.ch/board/, and the "Minimum URL match accuracy" is set to "Domain". So, it should work, but it didn't.

Then i changed the URL in the KeePass entry to https://ghisler.ch/board/login.php, and suddenly the Kee auto-logon for the TC forum worked again (also for the login form on thehttps://ghisler.ch/board page).

So, i changed the URL in the KeePass entry back to https://ghisler.ch/board/. Auto-logon continued to work. I disabled Kee, exited and restarted KeePass, and it is still working. I haven't restarted Firefox yet, so i don't know whether the issue i observed was some fluke, or whether there is some caching on the FF side at play. Well, i will update if the situation changes again...

**Comment by luckyrat** [comment]
If the situation does change again, please search the community forum for similar problems / websites and create a new discussion there if applicable - it's easier to discuss related issues and steps to reproduce on there. We can then create specific issues on GitHub for fixing problems with Kee if we find something actionable or keep information about workarounds, etc. in the same place.

https://forum.kee.pm

Thanks.
