### ISSUE TITLE
Search missing

### ISSUE THREAD

**Issue by chriss2142** [kee-org/browser-addon#82]
It seems that the old search field is removed.
I used this feature a lot to open pages or search for logins if the autodetect is not possible.
For me this means I have to switch to Keepass and than back to Firefox a lot.

I hope you can bring the search field als option back
Thanks for this plugin

**Comment by auanasgheps** [comment]
Please see https://github.com/kee-org/KeeFox/issues/823

**Comment by luckyrat** [comment]
Duplicate of #7
