### ISSUE TITLE
Trigger Change/Input Event after Autofill - is it gone forever?

### ISSUE THREAD

**Issue by auanasgheps** [kee-org/browser-addon#83]
Hey guys,
I've been testing Kee 2.0 on Chrome (just because on Firefox I'm stuck with v52 ESR due to missing add-ons) and so far looks and works great. 
There's one feature that is apparently missing and nobody has mentioned it: **Trigger Change Input Event after Autofill**.
This feature works great on KeeFox 1.7.2! It is needed because some websites don't allow to login (inactive login button) or show an error message if there is no "input" after filling.
Why is it missing? Is it just lack of time to re-implement, or it's another **pointless arguable limitation** of WebExtensions?

If possible, please add it in the future.

**Comment by luckyrat** [comment]
The code is the same as for KeeFox - https://github.com/kee-org/browser-addon/blob/bddde83a186ceacb232b5391946e8ebc43b4b53d/page/formFilling.ts#L283

So it should be working the same, albeit as a default behaviour with no option to disable it anymore. Can you provide some examples of where this event does not get triggered?

**Comment by auanasgheps** [comment]
Good to know the feature is still here.
So probably the issue is somewhere else.
It's the website here #84
