### ISSUE TITLE
No autofill when browsing a page, but login is matched

### ISSUE THREAD

**Issue by auanasgheps** [kee-org/browser-addon#84]
Hi guys

When visiting a login page ([Gearbest ](https://login.gearbest.com/m-users-a-sign.htm?type=1)in this example) no autofill occurs. 
![2017-11-15 09_48-sign in _ gearbest com](https://user-images.githubusercontent.com/20586878/32829485-2220e47c-c9ea-11e7-8e9c-156246aef771.jpg)
However, if I click on Kee icon within the field I can find my login, select it and eventually if will be autofilled.
![image](https://user-images.githubusercontent.com/20586878/32829558-4e9420b4-c9ea-11e7-8c5a-29c65e1c46b7.png)
![image](https://user-images.githubusercontent.com/20586878/32829701-c07e2422-c9ea-11e7-9344-dca0c2637fa8.png)

Yes I know it's a minor issue, I'm just curious why it happens.
Using Chrome v61 and Kee v2.0 B6.

I've checked the page code, this is the code for the username/email form. I believe "email" is either Text field name or Text field ID, already included in Kee whitelist.

`<input type="text" class="inputText" id="email" name="email" placeholder="Email" value="" autocomplete="off" style=[...]`

I could not manage to find extension logs in Chrome.

That's the configuration in KeePass, which looks right.
![image](https://user-images.githubusercontent.com/20586878/32830061-f085a374-c9eb-11e7-8258-f831272abda3.png)

I'm sure this is not the only website I've seen so far behaving in this way.
Do you have any recommendations?

**Comment by luckyrat** [comment]
Please search the community forum for similar problems / websites and create a new discussion there if still applicable with Kee 2.3 - it's easier to discuss related issues and steps to reproduce on there. We can then create specific issues on GitHub for fixing problems with Kee if we find something actionable or keep information about workarounds, etc. in the same place.

https://forum.kee.pm

Thanks.
