### ISSUE TITLE
Multiple users on same computer: conflicting port address

### ISSUE THREAD

**Issue by Magneticdud** [kee-org/browser-addon#85]
I noticed that if more than one user on the same computer use Kee, by default the plugin chooses the same port, and then there are infinite access requests between the two KeePass plugins.

Inexperienced users who doesn't know that the default port is the same can get confused by this

**Comment by luckyrat** [comment]
Yeah that's been the case forever. I'm not sure if there's anything that can be done to change it.

Possibly using a known port and offloading to another one for later communication - that may now be doable, potentially with the help of #23 but it's not that high up my list of priorities at the moment.

**Comment by Magneticdud** [comment]
Ah i was feeling that the old version didn't had this problem. Maybe i just didn't kept my KeePass open at the same time of the other user
