### ISSUE TITLE
Roku not showing "Save latest login"

### ISSUE THREAD

**Issue by ZathrasFive** [kee-org/browser-addon#86]
I'm not being offered the "Save latest login" option when I login at my.roku.com

Kee 2.0.0.25

**Comment by luckyrat** [comment]
Please continue this discussion at https://forum.kee.pm/t/kee-2-0-does-not-recognize-my-roku-com-login/314 - it's easier to discuss related issues and steps to reproduce on there. We can then create specific issues on GitHub for fixing problems with Kee if we find something actionable or keep information about workarounds, etc. in the same place.

Thanks.
