### ISSUE TITLE
Kee in Ubuntu 16.04

### ISSUE THREAD

**Issue by zetheroo** [kee-org/browser-addon#88]
Ubuntu 16.04
Firefox version 57 with Kee 2.0.0.25
Thunderbird 52.4.0 with KeeFox 1.7.2 
KeePass 2.37

What remains unclear to me is the integration of Kee with KeePass. 
With KeeFox I would have to copy the KeePassRPC.plgx from the Firefox/Thunderbird profile directory into /usr/lib/keepass2/plugins. At the moment I have the KeeFox 1.7.2 plugin file (from the Thunderbird profile) in that location, but Kee (used in Firefox) still works - previously you had to have the same version of KeeFox installed on both FF and TB for them to both work with KeePass - So is it now going to be that FF and TB can have different versions of KeeFox/Kee installed in either of them, and yet KeePass will still work with both!?

**Comment by dlech** [comment]
> So is it now going to be that FF and TB can have different versions of KeeFox/Kee installed in either of them, and yet KeePass will still work with both!?

Yes.

**Comment by zetheroo** [comment]
Well alright. Super! 
Now what about Kee and the installation of the plugin to KeePass in Linux - I could not find any KeePassRPC.plgx file in the Firefox profile folder.

**Comment by dlech** [comment]
I maintain a PPA with KeePassRPC if you like. Instructions: https://github.com/kee-org/KeeFox/wiki/en-%7C-Running-KeeFox-under-Mono

Or, you can grab the .plgx from here: https://github.com/kee-org/keepassrpc/releases
