### ISSUE TITLE
Infinite Login Reloads

### ISSUE THREAD

**Issue by jimmyswimmy** [kee-org/browser-addon#89]
Hi, first, thanks very much for updating Kee for FF57.  I am experiencing repeated logins - Kee enters a password, submits it, and the page reloads, over and over.

First, I have a workaround.  In Kee Options, disable "Forms with multiple matches should be automatically filled and submitted."  It seems that Kee is matching on multiple subdomains which all have the same domain.  If I do this, Kee doesn't submit.

Second, the problem may have to do with using a common password reference.  Instead of entering the password separately for all these subdomains, they reference a UUID in Keepass2 in the form {REF:P@I:UUID}.  Sometimes this doesn't work right, and I don't know how to diagnose that, but it looks like an extra-long password gets entered, possibly about the length of the UUID reference string instead of the actual password.

Third, I am pretty sure this wasn't happening the other day, after installing [what I think was] the last beta prior to the official release of Kee for FF57.  I don't know how to look up the version number.

I set logging to verbose and attached the resulting file.  I let it run several times and removed the intranet site address and replaced it with 'x'.  If you can't debug without that, let me know if there's anything I could do to help, otherwise I understand.

[Kee_logs.txt](https://github.com/kee-org/browser-addon/files/1478898/Kee_logs.txt)

I should say I am running FF 57.0, Kee release 11/14/17.

Thanks for reading and for all your work!

**Comment by luckyrat** [comment]
It's best to focus on the behaviour without any auto-submission first. It's likely that Kee is not able to submit this specific entry into this form but in any case, having auto-submission enabled is always liable to lead to infinite login attempts in a few cases and it sounds like this intranet site is one of them.

**Comment by jimmyswimmy** [comment]
In going back to that site, I find that when I let Kee enter the password on its own, and enters it, the site refreshes itself.  Looking at the network activity it appears that the main site is just reloaded from scratch.  This is why I get the infinite relogin attempts.

In Keepass's Kee Options tab I have set "Auto-submit" to Never.  This has had no effect.  The only approach which works is to use the copy password button under the login hamburger menu and manually pasting it.  Or, of course, typing the password in manually.

I'd love to know if there's anything else I can do to figure this out.  I've grown fond of Kee.

**Comment by luckyrat** [comment]
Hi,

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. I think that this issue now fits into the category of discussion that would be best held on the community forum rather than GitHub issues.

For that reason, I won't contribute further to this issue but please do get involved in any similar discussions on https://forum.kee.pm or create a new topic there if applicable. I think that https://forum.kee.pm/t/kee-is-autosubmitting-some-entries/415 is relevant.

Thanks,
Chris
