### ISSUE TITLE
Every time I unlock my Keepass, I'm prompted to put the verification code for Kee. Always

### ISSUE THREAD

**Issue by TheForgotten69** [kee-org/browser-addon#90]
As i said in the title, and I don't believe i saw this explained in the website or in issue. If so please excuse me, but it's rather annoying and don't know what's causing this or if it's the expected behavior. I use Firefox developper, the last version of KeePassRPC, and Kee.
Thanks for your time !

**Comment by luckyrat** [comment]
You might have High security mode enabled at one end or the other of your KeePassRPC connection.

**Comment by TheForgotten69** [comment]
Both are on medium :/ Do you know anything more ?

**Comment by TheForgotten69** [comment]
Problem solved when i did a clean install of windows. Don't know what causes the problem.
