### ISSUE TITLE
input fields with 'background: transparent !important' are not shown with Kee icon

### ISSUE THREAD

**Issue by t0lik** [kee-org/browser-addon#96]
I found out that fields where are set 'background <something> !important' style are not shown with Kee icon but still have clickable area at the right side with the logins popup.
Can we use a different way to show a clickable icon in the field or near it?

**Comment by luckyrat** [comment]
> Can we use a different way to show a clickable icon in the field or near it?

We can try sticking `!important` on each style we add.

E.g. replace:

https://github.com/kee-org/browser-addon/blob/ce00180239415c1c58f0cfbcde8039b5fbb6f374/page/keeFieldIcon.ts#L37

with:

`element.style.setProperty( "background-image", "url('" + image + "')", "important" );`

Might not be enough in this case but probably worthwhile for some other edge cases anyway, and we should consider doing that for the other icon style properties at the same time.

**Comment by t0lik** [comment]
Well, I suppose that '!important' usage is the bad practice among web-developers. And at the same time I don't see any convinient way to fix this more elegantly.

By the way, do you think about using VueJs to improve and make more easy developing of this webextension?

**Comment by luckyrat** [comment]
I've set !important on the background in [v2.4.8](https://github.com/kee-org/browser-addon/releases/tag/2.4.8)

I don't have any example of a page where this happened so can't test in the real world. If you can install the pre-release and test it @t0lik that would be helpful.

I'm planning to release a beta in a week.

**Comment by t0lik** [comment]
You can test on this page [Megafon](https://lk.megafon.ru/login/).
I 'll try to test 2.4.8 later.

**Comment by luckyrat** [comment]
Thanks for the link. I've tested and the Kee icon now appears as expected.

It looks like we might see an increase in the number of visual conflicts (such as with the password reveal eye icon on that page) but since this new version is a more accurate representation of what might happen when you click in that space and browsers offer us no way to avoid the problem, that's no reason to not release this improvement.
