### ISSUE TITLE
Tab through matched logins components

### ISSUE THREAD

**Issue by Roy-Orbison** [kee-org/browser-addon#98]
I hit `Ctrl + Shift + 2` to bring up logins dialogue (not a fan of it being un-draggable) then hit tab to try to select a login. The *Close* button can receive focus but the login list doesn't seem to be able to at all. It also looks deliberate since it uses `<li>`s, which aren't normally focusable and they also have `tabindex="-1"` on them.

**Comment by luckyrat** [comment]
Kee 2.2 will enable tabbing to the matched logins list.

See also #48 for once you get to the logins list.
